### ISSUE TITLE
Feature request: currently need to add double slash for line break

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#308]
Currently, to add a single line break you need to enter a double slash at the end of each line. It would be easier if the carriage return character added the line break without needing the double slashes.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2016-03-03T11:03:34Z):

----------------------------------------

This is by design. In most markup languages there are no real line breaks, only paragraphs.

**Comment by jendrikseipp** [comment]
*Original comment by* **a-reilly** (2016-03-03T11:25:26Z):

----------------------------------------

I know that, but for something that's used to make quick notes it would save time typing the slashes every time. But that's just my preference, thanks for the project anyway, it still works very well without that.

**Comment by noldsel** [comment]
Hi, maybe make it automatically add slashes when you press SHIFT + ENTER?
