### ISSUE TITLE
Displaying the latex formula

### ISSUE THREAD

**Issue by HeinrichGit** [jendrikseipp/rednotebook#325]
I tried as described [in this post](https://answers.launchpad.net/rednotebook/+question/171904) w/o success to display the latex formula

`\vec{x_k} = (\vec{p}, \vec{v}`

Any hint of how to do it ?

**Comment by jendrikseipp** [comment]
This feature is not officially supported, yet, but you can try:

$$\vec{x_k} = (\vec{p}, \vec{v})$$

**Comment by HeinrichGit** [comment]
Thanks. It worked so far for me.

**Comment by HeinrichGit** [comment]
Although, more complicated formulas wont be displayed
e.g..

$$
\begin{equation} \label{eq:statevars} 
\begin{aligned} 
\mathbf{\hat{x}}_k &= \begin{bmatrix} 
\text{position}\\ 
\text{velocity} 
\end{bmatrix}
\end{aligned} 
\end{equation}
$$

The two texts for example are displayed on the same raw (instead of in one column)

**Comment by jendrikseipp** [comment]
Multiline formulas are not supported for the time being.

**Comment by HeinrichGit** [comment]
Is there any list of what is being supported and what it is not ?
for example

\sigma_{pp}

is also not supported.

**Comment by jendrikseipp** [comment]
I recommend having a look at the MathJax documentation.
