### ISSUE TITLE
Russian translate combine with Greek words

### ISSUE THREAD

**Issue by Nick222** [jendrikseipp/rednotebook#329]
Russian translation combine with Greek words:

Menu: Format - 3 and 6 lines

What file I must edit to make it right?

**Comment by jendrikseipp** [comment]
I saw this issue recently as well, I think. Now it seems to be fixed. Can you try and check the latest version, please? Otherwise, you can have a look at `po/ru.po`.

**Comment by Nick222** [comment]
In po/ru.py two words missing, as I see:

#: ../rednotebook/gui/format_menu.py:110
msgid "Monospace"
msgstr "" --> "Моноширинный"

#: ../rednotebook/gui/format_menu.py:116
msgid "Clear format"
msgstr "" --> "Очистить форматирование"

**Comment by jendrikseipp** [comment]
Can you make a pull request please?

**Comment by Nick222** [comment]
I add another pull request...

And I cannot understand:

1) Where in RNB I can see this (I cannot find it`s place in GUI and cannot understand it`s meaning):

#: ../rednotebook/gui/options.py:188
msgid "Choose font"

#: ../rednotebook/gui/options.py:293
msgid "Edit font:"

#: ../rednotebook/gui/options.py:294
msgid "Preview font:"

2) In #: ../rednotebook/info.py:171

what meaning of words "You can add multiple entries to a single day by using different journals " - "journals" not different files? but what it is meaning...?

**Comment by Nick222** [comment]
And I cannot find in ru.po this text from RNB-options: "Show right-side tags pane" ...

**Comment by jendrikseipp** [comment]
1. I think these are in the Edit->Preferences dialog.
2. This just means that you can e.g. have a journal for work and another journal for your private notes.

**Comment by Nick222** [comment]
1. I cannot see "Preview font:" and "Edit font:" in the Edit->Preferences dialog at all.
2. This means two journals in one notebook, is not it?

**Comment by jendrikseipp** [comment]
1. You're probably using an outdated version then.
2. Notebooks, journals, directories with month files, they're all the same thing for RedNotebook.

**Comment by Nick222** [comment]
I use version from https://launchpad.net/~rednotebook/+archive/ubuntu/stable

**Comment by jendrikseipp** [comment]
There are different versions depending on the OS on that site. Please check Help->Info. If your version is less than 1.15, it's too old.

**Comment by Nick222** [comment]
My version RNB is 2.0
My OS - Xubuntu 17.04-64

**Comment by jendrikseipp** [comment]
For some strange reason "Preview font:" and "Edit font:" in the Edit->Preferences dialog are turkish for you. No idea why. 

What's your question again?

**Comment by Nick222** [comment]
I know why - because it is not translations on Russian for this commands.

**Comment by Nick222** [comment]
And where in ru.po this option name "Show right-side tags pane" - what number of it ?

**Comment by Nick222** [comment]
And where and when in RNB I can see this:
"../rednotebook/journal.py:205
msgid "Opening default journal."

**Comment by jendrikseipp** [comment]
The translation template hasn't been updated in a while. Now it is updated and the new strings will appear here soon (probably tomorrow): https://translations.launchpad.net/rednotebook/trunk/+pots/rednotebook/ru/+translate 
Then you can suggest your translations there.
