### ISSUE TITLE
Import from other formats

### ISSUE THREAD

**Issue by Nick222** [jendrikseipp/rednotebook#330]
I want to import data from files Zim, Lifeograph, HTML, ODT, special TXT and so on.

Where I can read about RNB-format and how to programming import?

(I enable Import command in menu (in menu.py) - but it cannot work at all (after window with formats))

**Comment by jendrikseipp** [comment]
I have started writing import functionality, but it's currently commented out in the code. You'll have to uncomment it and probably fix some code rot. You can read about the format in the help file (Ctrl+H).

I wonder if it wouldn't be better to implement import functionality in external scripts that produce RedNotebook month files. Then RedNotebook would only have to import and merge the contents of one file format.
