### ISSUE TITLE
Cannot show image with non-latin symbols in file name

### ISSUE THREAD

**Issue by Nick222** [jendrikseipp/rednotebook#331]
Xubuntu 17.04-64
RNB 2.0 from daily PPA

Cannot show image with non-latin symbols in image-file name - and show with only Latin symbols in file name.

**Comment by Nick222** [comment]
Image1 (edit) https://preview.ibb.co/hDcuPa/Latin_Nonlatin1.png
Image2 (preview) https://preview.ibb.co/n6kLxv/Latin_Nonlatin2.png

**Comment by jendrikseipp** [comment]
Thanks! I could confirm this on my machine. Even German umlauts are problematic.

**Comment by michote** [comment]
Same here with German umlauts in file or image paths.
Ubuntu 18.04
RNB 2.6.1

**Comment by jendrikseipp** [comment]
Thanks Paweł!
