### ISSUE TITLE
Cannot see arrow to open day-template

### ISSUE THREAD

**Issue by Nick222** [jendrikseipp/rednotebook#333]
Xubuntu 17.04-64
RNB 2.0 from daily PPA

In RNB main toolbar icon for paste weekday template is without any arrow - and I cannot open pop-down menu to open another template.

**Comment by jendrikseipp** [comment]
For this and the other issues you opened, it would be good if you could provide screenshots of your problems.

**Comment by Nick222** [comment]
But how I can attach picture file?

**Comment by jendrikseipp** [comment]
You'll have to upload it somewhere and post a link here, I guess.

**Comment by Nick222** [comment]
Image https://image.ibb.co/nBW7AF/NoArrow.png

**Comment by jendrikseipp** [comment]
The arrow next to the icon has been removed in version 2.0, you can just click the icon.
