### ISSUE TITLE
Export to PDF doesn't work if certain special characters are used in journal text

### ISSUE THREAD

**Issue by taosxx** [jendrikseipp/rednotebook#336]
PortableApps Rednotebook 1.15 (Windows 7)

If I use special characters in the journal text such as ↳ (U+21B3) or ≙ (U+2259) and then try to export the journal to pdf, the export stops prematurely (the file is much smaller than it should be) and the resulting pdf file can't be opened (Adobe Acrobat complains about a damaged file which can't be repaired).

**Comment by jendrikseipp** [comment]
The development version dropped PDF exports since the feature was rather brittle. Instead, you can export to HTML, open the result in a browser and print it to PDF.
