### ISSUE TITLE
Slovak (sk) translation update

### ISSUE THREAD

**Issue by slavkoja** [jendrikseipp/rednotebook#337]
I don't know where to add translation and my launchpad account expired long time ago, then i hope that here it will be OK.

Slovak translation attached - one term stays untranslated, because i am not sure what this is.

[sk.po.zip](https://github.com/jendrikseipp/rednotebook/files/1180514/sk.po.zip)

**Comment by jendrikseipp** [comment]
Thanks for your work. Unfortunately, I can't accept the strings that way. Can you please raise a pull request?

**Comment by slavkoja** [comment]
OK, your repo, your rules.

But for me it is not acceptable to clone whole repository only due translation, then i will stay to maintain this translation for itself only.

regards
