### ISSUE TITLE
After recent update, will not launch. Needs python3-yaml

### ISSUE THREAD

**Issue by stockphrase** [jendrikseipp/rednotebook#339]
Red Notebook won't launch after recent update. When selecting the program, the "hourglass" spins to show that the program is trying to start, but it just dies silently after. 

I ran in terminal, and it is looking for PyYAML. 

Installed `python3-yaml` and then the program started. 

This behavior began after the recent update.

**Comment by jendrikseipp** [comment]
Thanks for the info. That's strange, since python3-yaml is already in the list of required libraries in the debian/control file.

**Comment by jendrikseipp** [comment]
Did you install RedNotebook by adding the PPA or by manually downloading the .deb package?

**Comment by stockphrase** [comment]
Looks like I'm on PPA.

**Comment by jendrikseipp** [comment]
Fixed in a recent release.
