### ISSUE TITLE
Some menu items are in Russian for en_GB locale 

### ISSUE THREAD

**Issue by pasimako** [jendrikseipp/rednotebook#340]
![015](https://user-images.githubusercontent.com/10180928/28996009-46ce9594-79ef-11e7-9dc3-1eb3b8bb3c7d.png)

I have installed `2.1.2-0~201708022235~ubuntu17.04.1` package from the stable PPA. When I start the program from the shell with `rednotebook` or `LANGUAGE=en_GB rednotebook` some menu items appear in Russian. My system locale is en_GB. I have to run `LANGUAGE=en_US rednotebook` to get all menu items in English.

**Comment by jendrikseipp** [comment]
Thanks for the report! I have fixed this in e8bec1f2bc0534a87e8d4a66f8ffa030f8d02d02. A new version should pop up soon in the stable PPA.
