### ISSUE TITLE
Feature request : Adjusting size of an image to fit with the page (in Latex output)

### ISSUE THREAD

**Issue by ccrptl** [jendrikseipp/rednotebook#341]
Adjusting size of an image to fit with the page, irrespective of original image dimension. 
Latex can take care of this by setting figure width to "line width" or "page width" while maintaining the aspect ratio. Alternately, these options can be made available in preferences.

A sample latex code for this implementation : 
`\begin{figure}[ht]
\centering
     \includegraphics[width=1.0\textwidth]{image.png}
     \caption{this is figure caption}
     \label{this is figure label}
\end{figure}` 

Ref : [https://tex.stackexchange.com/questions/39147/scale-image-to-page-width](url)

**Comment by jendrikseipp** [comment]
Since this request is Latex-specific, I recommend to just include the Latex source in the day's text:

```
'''
\begin{figure}[ht] \centering \includegraphics[width=1.0\textwidth]{image.png} \caption{this is figure caption} \label{this is figure label} \end{figure}
'''
```
