### ISSUE TITLE
Rednotebook has been removed from Debian 9 (Stretch)

### ISSUE THREAD

**Issue by tomassenabre** [jendrikseipp/rednotebook#347]
Hello,
I am trying to install rednotebook on my computer with Debian 9 and the package has been removed from the repositories.

[RM: rednotebook -- RoQA; depends on unmaintained python-webkit]https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866617(url)

Thank you for your work
regards

**Comment by jendrikseipp** [comment]
@kathenas is currently working on adding a new package to Debian (see also #343). For the time being you'll probably have to try the Ubuntu packages from the stable PPA or run from source.

**Comment by tomassenabre** [comment]
OK thanks.  I will try to run from source.

**Comment by kathenas** [comment]
The Intention To Package (ITP) for debian and submission for inclusion will happen this weekend.

**Comment by tomassenabre** [comment]
Great. Thanks for your job

**Comment by jendrikseipp** [comment]
@sandrotosi: thanks again for your work on the txt2tags Debian package! Maybe you could help us out here as well: we failed to get RedNotebook back into Debian. Would you be interested in giving it another try?

**Comment by sandrotosi** [comment]
Sorry @jendrikseipp but i noticed rednotebook has been completely removed from Debian, so the work required would be quite higher than what i did for txt2tag. but maybe @tiger-jmv (the former Debian maintainer) may be interested to know there's new development happening here

**Comment by jendrikseipp** [comment]
OK, could you maybe ping him? The handle you used doesn't seem to exist on Github.

**Comment by carygravel** [comment]
Isn't it back, now? Can't this be closed?

**Comment by jendrikseipp** [comment]
Good point, thanks!
