### ISSUE TITLE
external/txt2tags.py - Incompatible GPL-2  license in conjunction with GPL-3+

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#354]
I have been informed by debian mentor(s) that the GPL-2 licensed txt2tags.py is not compatible with GPL-3+.

Can we research and address this supposed issue?

**Comment by jendrikseipp** [comment]
GPL-2 is in fact incompatible with GPL-3+ (https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility). Fortunately, txt2tags.py has been relicensed under GPL-2+ shortly after I copied the file into the RedNotebook repository: txt2tags/txt2tags@716debb6ae7996e21201a74cfa6a30cb8b2532fe. Judging by the commit message it seems that GPL-2+ was the intended license all along. 

I suggest to update the license info in rednotebook/external/txt2tags.py and debian/copyright (with regards to txt2tags) to GPL-2+. @aureliojargas, would you be fine with this solution?

**Comment by kathenas** [comment]
That is great and I am very happy with that. I thought we may be in for a horrid protracted license game, but appears not. :-)

**Comment by kathenas** [comment]
If you do txt2tags.py. I will deal with debain/copyright.

**Comment by aureliojargas** [comment]
@jendrikseipp Sorry coming so late. That's ok, I don't mind about licenses.
