### ISSUE TITLE
external/txt2tags.py - Again...

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#358]
Clarification needed re: external/txt2tags.py

The facts:

* txt2tags release version is 2.6 (2010)
* txt2tags has had no release since but many commits.
* external/txt2tags.py in rednotebook has had modifications since txt2tags last release date.

Questions:

* Is external/txt2tags.py up to date with upstream txt2tags?
* Does external/txt2tags.py have local modifications that are not in upstream txt2tags?

Let the discussion commence. :-)

**Comment by jendrikseipp** [comment]
> Is external/txt2tags.py up to date with upstream txt2tags?

external/txt2tags.py was "branched" off upstream txt2tags between the upstream 2.5 and 2.6 releases. I also modified external/txt2tags.py slightly. external/txt2tags.py is therefore quite different from any official txt2tags release.

> Does external/txt2tags.py have local modifications that are not in upstream txt2tags?

Yes, it does. For example, one of the upstream authors doesn't want txt2tags to support Python 3 (https://github.com/txt2tags/txt2tags/issues/181#issuecomment-284526543), so I made the required changes in external/txt2tags.py.

**Comment by kathenas** [comment]
OK, this being the case...

* external/txt2tags.py needs to be updated to match the commit below (at least [1]) as you cannot cherry pick a copyright change even if the file has been modified by a third party.

https://github.com/txt2tags/txt2tags/commit/716debb6ae7996e21201a74cfa6a30cb8b2532fe

[1] I would be tempted to pull the whole file at the commit above, reapply subsequent modifications and leave no doubt when a fork of the file took place and licensing could then not be questioned if it is GPL-2+ or not.

* debian/copyright entry for external/txt2tags.py needs to match the copyright dating from the above commit.

* As a contributor to this file. You need to be added to debian/copyright for external/txt2tags.py.

* It maybe prudent to add a note to external/txt2tags.py that the file does not match upstream and has been modified.

**Comment by jendrikseipp** [comment]
That makes sense. I rebased my changes onto txt2tags 2.6 and made the changes you suggested. Feel free to reopen if something is missing.
