### ISSUE TITLE
Image files not showing in file selector (Both Mac and Win)

### ISSUE THREAD

**Issue by milysun** [jendrikseipp/rednotebook#359]
Hi there,
I have been trying so hard to get the Rednotebook Ver 2.2 installed and running natively on my Macbook pro (not the wine bundle), however I noticed I could not insert any images because nothing is shown in the file selector. I've checked the Gdkpixbuf module through "pixbuf.Pixbuf.get_formats()", and it looks normal as all image formats are listed, and can be loaded if I specify a filename in python.

So I thought maybe something else is broken with my mac installation, however the windows version has the same problem. It can find neither png nor jpeg, so this could be a bug or something for Ver 2.2? P.S, Drag and drop doesn't work either.

Also, I am syncing my notes using Dropbox (or any other platform alike), it would be ideal to actually copy the image files into rednotebook/data folder and use relative path for display, then the pictures can be synced together with the text in the future version. Screenshots for both system attached as follows:
![macrnb](https://user-images.githubusercontent.com/19829189/30406868-fe00cb94-9937-11e7-896d-95c8c9a5372a.png)
![windowsrnb](https://user-images.githubusercontent.com/19829189/30406873-0418782e-9938-11e7-84ca-e1f0bb683603.png)

Thanks for reading this.

**Comment by jendrikseipp** [comment]
Thanks for the report! I fixed this in the repo. Would you care to write up how to run RedNotebook 2.2  natively on Mac OS? This may be very useful for others.

**Comment by jendrikseipp** [comment]
PS: Copying the files into the journal directory is planned.

**Comment by milysun** [comment]
Basically the blog back in 2010 is the guideline.
https://jamesthedisciple.wordpress.com/2010/04/09/rednotebook-on-osx-how-to/

I've tried both the jhbuild method to compile and also used "brew install pygobject3 --with-python3 gtk+3". However because I used anaconda for my python3, the gi package was not installed to the correct directory and could not be found. 
I realised this too late and wasted too much time compiling different version of modules, so I can't really tell the minimal necessary steps need to be taken. Eventually I found the gi package folder should be placed under anaconda directory and move it over, problem solved and the RNB runs happily. I also install gdk-pixbuf2 through homebrew but as I said I have no idea if it's necessary or sufficient. Only additional package required is the gnome-icon-theme otherwise RNB can not find correct icons.

As for picture selecting, does it work on your computer after the fix?
I also tried to add individual mime_types to filter like what you have done, however it did not work.
If the gui/insert_menu.py is the only change, then unfortunately it's still not working for me after the patch. Thanks.

**Comment by jendrikseipp** [comment]
Thanks for describing the installation! I'll probably use your information to update the info in the blog post and publish it somewhere on the downloads page.

Regarding picture selection, that's curious indeed. I could confirm that picture selection doesn't work on Windows either, but with my gui/insert_menu.py change now it does. Have you tried disabling the Gtk.FileFilter altogether by commenting out the line `picture_chooser.add_filter(filter)`?

**Comment by milysun** [comment]
> commenting out the line picture_chooser.add_filter(filter)

Yes, this does the trick! Although I really ignorant and have no idea at all on why the filter should not be added.

After commenting this out, images are displayed in the file selector and can be inserted into the notebook. And the filter.add_mime_type("image/*") can stay as it, not need to add each individual image types.

Thanks heaps for the fix. And please do implement the image copying function in the future, most pictures will move around or get deleted, so the link will expire if RNB don't keep a local copy itself.

**Comment by jendrikseipp** [comment]
Thanks for testing. It would be interesting to see if only the add_mime_type is broken on MacOS or also the add_pattern. Could you try the following code, please?

```
filter = Gtk.FileFilter()
filter.set_name("Images")
filter.add_pattern("*.jpg")
filter.add_pattern("*.jpeg")
filter.add_pattern("*.png")

picture_chooser.add_filter(filter)
```

Can you see the jpg files afterwards?

**Comment by milysun** [comment]
Nop, doesn't work.
The "picture_chooser.add_filter(filter)" is the problem. 
After commenting this line out, the .add_pattern also works fine.

**Comment by jendrikseipp** [comment]
Thanks. If add_filter is commented out, all add_pattern and add_mime_type calls are ignored (since the filter is never applied). But based on your observations, neither add_pattern nor add_mime_type seem to work on MacOS. I updated the code accordingly.

**Comment by milysun** [comment]
Right. Didn't notice this because I was testing it from a folder with only pictures. And now I can see all file types are displayed thus the filter is actually disabled. 
Since there were multiple errors while I compile the gtk3 using jhbuild, this is very likely to be my problem instead of MacOS. Please leave the filtering option in the code as is, and I can live with it as long as pictures can be inserted without filtering function.
Thanks a lot.

**Comment by jendrikseipp** [comment]
The filtering function is not essential. Removing it is better than having some users that don't see any files, I think.
