### ISSUE TITLE
Signing tags/releases

### ISSUE THREAD

**Issue by ghost** [jendrikseipp/rednotebook#363]
Wishlist. ;-)

Can future tags/releases be signed?

For debian, this can be then setup so **uscan** can then verify release tarballs that are used for packaging.

Reference:

External link: [Creating Signed GitHub Releases](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Comment by jendrikseipp** [comment]
Thanks for the suggestion! For now, however, I don't think signed releases are valuable enough to warrant the overhead.
