### ISSUE TITLE
Function request -- Free scrolling of the page

### ISSUE THREAD

**Issue by milysun** [jendrikseipp/rednotebook#365]
Hi Jendrik,

When a lot of lines are entered in the RNB, the page can not be scrolled to move the lines up to the middle of window, so the current editing line is alway at the bottom of the screen/window, which is a quite awful editing experience. Could you please make the page freely scrollable regardless where the cursor is?

I also noticed the fonts are scaled differently on my macbook pro with external monitor plugged in or not. The same font setting looks half the size if an external monitor is not plugged in. I know this must be an OSX feature and as you don't run RNB on mac you probably won't be able to test and fix. However since most main stream editing apps does not have such issue, there should be a standard solution for such scaling issue on Mac?

Thanks.
Chao

**Comment by jendrikseipp** [comment]
I suspect that both the scrolling and the scaling issue are caused by the underlying GTK library on MacOS. There's probably nothing RedNotebook can do about these issues. To test this, can you please run the small example editor app from https://python-gtk-3-tutorial.readthedocs.io/en/latest/textview.html? Do the two issues occur there as well?

**Comment by milysun** [comment]
Arhh right, this simple editor behaves the same as RNB on my MBP, won't scroll freely. 
Sorry I should at least test on my Windows machine before posting any question, considering my Mac installation is really a guinea pig with many questionable modules. 
Anyway, I can "fix" this by using a template with many empty lines at the bottom of page, so it will scroll at least to the middle of page. No big deal at all.
Please close this ticket.

**Comment by jendrikseipp** [comment]
Well, you may be able to get this fixed if you report the issue(s) with the minimal app example to the GTK devs at https://bugzilla.gnome.org/.
