### ISSUE TITLE
error message on OSX 10.9.5 

### ISSUE THREAD

**Issue by Softskills** [jendrikseipp/rednotebook#368]
on Mac 10.9.5)  I have this error message on start up of rednotebook. (I did instal with Macports, easy)
~$  rednotebook
** (process:1030): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'
rednotebook does start, so no big problem there. 
Can only start rednotebook in terminal.

**Comment by jendrikseipp** [comment]
Thanks! The warning comes from the underlying pygobject library. The issue has been fixed there, but it might be a while until it becomes available for Windows. You can safely ignore the warning though.
