### ISSUE TITLE
Statistics can only be used once per session

### ISSUE THREAD

**Issue by hlinhn** [jendrikseipp/rednotebook#370]
I am using RedNotebook version 2.3 Ubuntu 16.04. If statistics window is opened once, subsequent call to it won't show any information - in other directories or in the same directory. The notebook must be restarted before the statistics window can be used again.

**Comment by jendrikseipp** [comment]
Thanks! I can confirm the issue.

**Comment by tossia** [comment]
Sorry, but even after restarting, the statistic doesn't work.
