### ISSUE TITLE
Missing font in Windows 7? Only squares in GUI

### ISSUE THREAD

**Issue by taosxx** [jendrikseipp/rednotebook#372]
Just upgraded to Rednotebook 2.3 Portable on Windows 7:

All characters (GUI + journal text) are replaced by squares (see Screenshot).
![bug_rednotebook](https://user-images.githubusercontent.com/13113555/31483248-d9b50d90-af2b-11e7-9b38-131e200b06f8.png)

I should add that this only happens if you upgrade from an older version such as 1.15. If you install 2.3 in a new directory there's no problem with the font.

It seems that in the case of an upgrade fonts.conf is missing from RedNotebookPortable/Data directory. If I copy the file to the upgraded installation the squares are again replaced by proper characters.

**Comment by jendrikseipp** [comment]
The solution seems to be to uninstall the old version before installing the new version (https://answers.launchpad.net/rednotebook/+question/659284). I reported the problem to the main portableapps developer.

**Comment by JohnTHaller** [comment]
First, for anyone else reading this, do not unininstall and reinstall the portable app.  It will remove your settings.  This will fix the issue, but it is overkill.

Second, I think what happened is you did an upgrade after RedNotebook was not shut down correctly (crash or Windows closed it, which is similar to a crash) so config files were left outside the Data directory.  When this happens, currently you will lose your fonts.conf and files like gtkfilechooser.ini, .gtk-bookmarks, .recently-used.xbel, and WebpageIcons.db will be left behind on the local machine. Normally, the next time you run RedNoteBook Portable, it will recognize this and recover from the improper shutdown.  If you upgrade after an improper shutdown, the fonts.conf file is wiped out and can't be recovered.   As you noted, you can fix this by manually copying the fonts.conf from the RedNotebookPortable\App\DefaultData directory to your RedNotebookPortable\Data directory.

Third, I've updated the installer's configuration to properly: https://github.com/PortableApps/AppConfigs/commit/4ee5537a12be291bde4db68188fe0612bbbd82a5

**Comment by jendrikseipp** [comment]
Thanks @JohnTHaller for clarifying!
