### ISSUE TITLE
Question: Where to obtain the "optional Webkit"?

### ISSUE THREAD

**Issue by DendrocoposMajor** [jendrikseipp/rednotebook#373]
From the change log: "Make webkit optional (but highly recommended)".
On Windows this makes Rednotebook if not useless at least a whole lot less useful.

Seems like it [Webkit] is not exactly easy to find? Is it build your own that is the order of the day or are there prebuilt suitable binaries available somewhere?

**Comment by jendrikseipp** [comment]
Unfortunately, webkit has dropped support for Windows altogether, so there's no point in trying to find it or compile it. The best way of restoring internal previews on Windows is to use the Chromium Embedded Framework, see #369 .
