### ISSUE TITLE
Left window margin short

### ISSUE THREAD

**Issue by BarefootWarrior** [jendrikseipp/rednotebook#376]
### Versions

RedNotebook version: 2.3

Operating system and version: Ubuntu Budgie 17.10

### Steps to reproduce the behavior Open Rednotebook

![screenshot from 2017-10-28 13 52 41](https://user-images.githubusercontent.com/32079130/32131047-e0c72d84-bbe7-11e7-9127-a313bfdc2050.png)

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

**Comment by jendrikseipp** [comment]
I'll make the left pane bigger by default. For now, you can just slide the left separator line to the right.

**Comment by BarefootWarrior** [comment]
Perfect Jendrik, too easy (why did I not think of that). Thank you for a quick reply. That is tops.

**Comment by jendrikseipp** [comment]
Let's leave this issue open until I fix the default setting.

**Comment by jendrikseipp** [comment]
Could you please open $HOME/.rednotebook/configuration.cfg, delete the line containing "leftDividerPosition", save the file, open RedNotebook and report whether the left divider is too far left?

**Comment by jendrikseipp** [comment]
Or even better: Open RedNotebook, move the slider to the leftmost position that still lets the left panel fit within the margins, close RedNotebook, then tell me the value for "leftDividerPosition" in the file  $HOME/.rednotebook/configuration.cfg.

**Comment by jendrikseipp** [comment]
This should be fixed in 2.12.
