### ISSUE TITLE
Copy-Paste with cursor doesn't work in linux

### ISSUE THREAD

**Issue by leonpollak** [jendrikseipp/rednotebook#378]
### Versions
2.3
RedNotebook version: 
2.3
Operating system and version:
FC25
### Expected behavior
Marking with mouse left button and pasting with middle button should work.
### Actual behavior
No pasting is performed
### Steps to reproduce the behavior
Mark some text with mouse left button, try to insert with mouse middle button
### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

**Comment by jendrikseipp** [comment]
Marking and pasting with middle-click works for me using Ubuntu 16.04. Probably your configuration is messed up a bit :-) Feel free to reopen if you find that the failure is caused by RedNotebook.
