### ISSUE TITLE
Feature request: Count characters

### ISSUE THREAD

**Issue by rrcgat** [jendrikseipp/rednotebook#379]
### Versions
RedNotebook version: 
2.3

Operating system and version:
Arch Linux

Hello Jendrik, sometimes I want to count the characters on my note, maybe it can be done by rednotebook itself so I don't have to copy the text to another software. ^_^

**Comment by jendrikseipp** [comment]
Counting the characters in the currently visible day is already possible via Journal->Statistics. Unfortunately, the statistics dialog is broken and only works once per session (see #370).
