### ISSUE TITLE
Add Checksums to the Releases

### ISSUE THREAD

**Issue by TheClonker** [jendrikseipp/rednotebook#381]
Meta Issue with the Repository so no Template

Hello,
i was wondering if it would be possible for you to add Checksums for your Releases on Github to verfiy the integrity of the Download ?

**Comment by jendrikseipp** [comment]
I'll look into that :-)

**Comment by kathenas** [comment]
This is essentially a duplicate of #363

**Comment by jendrikseipp** [comment]
Closing this, since it's a duplicate.
