### ISSUE TITLE
Convert sourceforge project page to use HTTPS

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#383]
Currently the rednotebook project page uses http.

http://rednotebook.sourceforge.net

Really this needs to be using https.

Below is relevant sourceforge page section to do this.

https://sourceforge.net/p/forge/documentation/Project%20Web%20Services/#https

**Comment by jendrikseipp** [comment]
Thanks for the hint! I didn't know it was that easy to change this :-)

**Comment by jendrikseipp** [comment]
The new link is https://rednotebook.sourceforge.io

**Comment by kathenas** [comment]
Just the the link in the github project description and I think they are changed then. :-)

**Comment by jendrikseipp** [comment]
Done :)
