### ISSUE TITLE
Line breaks not working for lists in browser preview mode

### ISSUE THREAD

**Issue by TechGirl00** [jendrikseipp/rednotebook#387]
### Versions

RedNotebook version: 2.3

Operating system and version: Windows 10 Home

### Expected behavior: 
To see lists (in my case numbered) break properly after each line Ex:
1. This is the first line in my list.
2. This is the second line in my list.
3. This is the third line in my list.
4. This is the fourth line in my list.

It works fine in RedNotebook. It's just no working in browser mode.

### Actual behavior: 
There is no break after each line in preview mode so it produces a run-on paragraph. Ex:
1. This is the first line in my list. 2. This is the second line in my list. 3. This is the third line in my list. 4. This is the fourth line in my list.

It's like the HTML break tag is missing. Paragraphs are working fine. I tested this with multiple browsers: Chrome, IE and Edge and the behavior is the same. I'm assuming this would happen regardless of the numbers given this isn't actually a numbered list. Let me know if you still need the rednotebook log for this. I took a look and it didn't indicate anything related to this. Just text about adding the pictures I inserted and saving.

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

**Comment by jendrikseipp** [comment]
RedNotebook doesn't use markdown as its markup language (at least not for now). It uses txt2tags (https://txt2tags.org/markup.html) where numbered list items start with a "+".
