### ISSUE TITLE
GUI hangs when using more than one template per session

### ISSUE THREAD

**Issue by coolmast** [jendrikseipp/rednotebook#388]
I am using RedNotebook version 2.3 on ArchLinux. If I inserted any template once in a session, the gui hangs up on subsequent tries. I then need to restart RedNotebook and can insert the next template. 
When restarting the notebook, the original text for the day where I tried to paste the second template is gone but replaced with the unprocessed template content, i.e. it still contains `$date$` which has not been resolved to the actual date.

There is no entry created in the log when clicking the second time on any template.

**Comment by jendrikseipp** [comment]
Unfortunately, I can't reproduce the error on my end. Could you please post the contents of one of the template files and the template filename here, please?

**Comment by jendrikseipp** [comment]
Feel free to reopen this issue if the problem persists.
