### ISSUE TITLE
Can sometimes save & insert template and others not

### ISSUE THREAD

**Issue by dabeegmon** [jendrikseipp/rednotebook#391]
### Versions

RedNotebook version: 2.3

Operating system and version: Debian stretch (10 or testing)

### Expected behavior
Have a created template (Information I want to collect over the day).
Most times when I go to 'template' and chose the one in question and select the template shows but the top buttons are greyed and it is not possible to write anything or do anything. 

### Actual behavior
Need to quite 'Rednotebook' and then restart it. 
Date with selected template is present. 
It is then possible to enter the template in the next instance and the buttons are 'not' greyed rather blue and it is possible to choose save & insert or . . .  .

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

2018-01-16 19:03:39,449 INFO     Nothing to save
2018-01-16 19:13:39,447 INFO     Wrote file /home/memyself/.rednotebook/data/2018-01.txt
2018-01-16 19:13:39,448 INFO     The content has been saved to /home/memyself/.rednotebook/data
2018-01-16 19:13:39,448 INFO     The content has been saved to '/home/memyself/.rednotebook/data'

May be related to #388.

Hope this is enough information. Please ask if more information is needed.

**Comment by dabeegmon** [comment]
in 'Actual behavior' meant 'Need to quit . . .  .' not quite!

**Comment by jendrikseipp** [comment]
Could you please post the contents of the template file and the template filename here, please?

**Comment by jendrikseipp** [comment]
Feel free to reopen if the problem persists.
