### ISSUE TITLE
[Feature Request] Search terms don't need to be consecutive.

### ISSUE THREAD

**Issue by MAShah-UK** [jendrikseipp/rednotebook#392]
### Versions

RedNotebook version: 2.3
Operating system and version: Windows 10
### Expected behavior
If the user enters multiple search terms, the program should check to see if those search terms appear at any point within a dairy entry. If all of the search terms have been found at least once, then the diary entry should come back as a positive match. Alternatively, regular expressions could be supported by the search tool.

The idea is that sometimes a user may remember multiple things happening in a certain day, but they may not remember the consecutive words that they typed.
### Actual behavior
The program looks for an exact match of search terms.
### Steps to reproduce the behavior
You can see that the search tool only brings back entries which have an exact match of the search string.

**Comment by jendrikseipp** [comment]
This has been implemented for version 2.4. If something's not working feel free to reopen.
