### ISSUE TITLE
Ubuntu PPA for Rednotebook: apt downgrade loop for debhelper and dh-autoreconf

### ISSUE THREAD

**Issue by michaelpeeters** [jendrikseipp/rednotebook#393]
### Versions

RedNotebook version: 2.3

Operating system and version: 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
using the Ubuntu 16.04 PPA, the updates should go fine

### Actual behavior
the apt process constantly tries to _Downgrade_ debhelper/dh-autoreconf. 

### Steps to reproduce the behavior
- use the PPA for rednotebook on Ubuntu 16.04 (64bit): ``sudo add-apt-repository ppa:rednotebook/stable ``
- ``sudo apt update ; sudo apt install rednotebook``
- now run ``sudo apt upgrade``

### Log output when reproducing behavior
```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be DOWNGRADED:
  debhelper dh-autoreconf
0 upgraded, 0 newly installed, 2 downgraded, 0 to remove and 0 not upgraded.
Need to get 854 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/rednotebook/stable/ubuntu xenial/main amd64 dh-autoreconf all 12~ubuntu16.04.1 [16,0 kB]
Get:2 http://ppa.launchpad.net/rednotebook/stable/ubuntu xenial/main amd64 debhelper all 10.2.2ubuntu1~ubuntu16.04.1 [838 kB]
Fetched 854 kB in 0s (1.325 kB/s)  
(Reading database ... 352007 files and directories currently installed.)
Preparing to unpack .../dh-autoreconf_12~ubuntu16.04.1_all.deb ...
Unpacking dh-autoreconf (12~ubuntu16.04.1) over (12~ubuntu16.04.1) ...
Preparing to unpack .../debhelper_10.2.2ubuntu1~ubuntu16.04.1_all.deb ...
Unpacking debhelper (10.2.2ubuntu1~ubuntu16.04.1) over (10.2.2ubuntu1~ubuntu16.04.1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up dh-autoreconf (12~ubuntu16.04.1) ...
Setting up debhelper (10.2.2ubuntu1~ubuntu16.04.1) ...
```
--> same error returns. 

### reference
See also other reports:
- https://askubuntu.com/questions/1005301/downgrade-package-loop
- https://askubuntu.com/questions/961938/how-do-i-stop-continuous-downgrading-by-apt

**Comment by jendrikseipp** [comment]
Thanks for the report! I removed the two packages from the PPA (they should no longer be needed). Removal takes some time, but I guess that after a few hours (or maybe days) the issue should go away. If it doesn't, feel free to reopen this issue report.
