### ISSUE TITLE
Tray control

### ISSUE THREAD

**Issue by smaragdus** [jendrikseipp/rednotebook#394]
I would like to suggest a simple enhancement- tray control- right-click on RedNotebook tray icon- 2 commands:

- Show
- Quit

Single left click is fine for for restoring program window but if "Close to tray" is enabled the users need to maximize RedNotebook in order to exit it.

**Comment by jendrikseipp** [comment]
The tray menu should already have these two options, i.e. "Show" and "Quit". If this is not the case for you, can you please provide a screenshot? I'd also be interested in the contents of rednotebook.log.

**Comment by smaragdus** [comment]
@jendrikseipp 

On my system (Windows 8 x64) single right click maximizes RedNotebook, right click does nothing.

Of course I can take a screen-shot but you will only see the tray icon and no commands since as I said right-click does nothing.

Preferences- "Close to system tray" enabled.

**Comment by albsanrom** [comment]
@jendrikseipp 

On my system (Windows 10) when I right-click on the tray icon it closes the app. I actually like it like that, but I'm not sure that's on purpose.

This is what shows up in rednotebook.log:
```
[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "C:\repo\rednotebook\gui\main_window.py", line 340, in on_tray_popup_menu
  File "C:\Python344\lib\site-packages\gi\overrides\__init__.py", line 39, in __getattr__
  File "C:\Python344\lib\site-packages\gi\module.py", line 137, in __getattr__
AttributeError: 'gi.repository.Gtk' object has no attribute 'status_icon_position_menu'
```

**Comment by jendrikseipp** [comment]
Thanks, @albsanrom ! I hope my last commit fixes the problem you're seeing. Could you test it, please, by running the following installer? https://ci.appveyor.com/api/buildjobs/j164r6y6yxdkmkaw/artifacts/rednotebook-2.14.exe

**Comment by albsanrom** [comment]
@jendrikseipp Great! It seems to be fine now.

**Comment by jendrikseipp** [comment]
Awesome, thanks for testing!

@smaragdus is the original issue solved by this fix as well?

**Comment by smaragdus** [comment]
@jendrikseipp 

I downloaded and tested the installer you provided above and I can confirm that under Windows 8 tray commands appear on tray icon right click, screen:

![RedNotebook 2 14 - 2019-12-02 - 004](https://user-images.githubusercontent.com/9025757/69964256-b3e9d300-151a-11ea-9692-68d48102a2f7.png)

Thank you for fixing the problem. I am closing this issue.

**Comment by jendrikseipp** [comment]
Perfect, thanks!
