### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by ScumCoder** [jendrikseipp/rednotebook#396]
### Versions

RedNotebook version: 2.4 (the issue happened somewhere between 1.10 and 2.4, since I was happily using 1.10.1 for a long time, until spellcheck stopped working and I was forced to update).

Operating system and version: Ubuntu 16.04.4 LTS (Xenial Xerus)

### Expected behavior

1) The text search works with partial word match.
2) The text search works in case insensitive mode.

### Actual behavior

1) Trying to search the word without typing one or more leading letters never works.
2) Trying to search the word without typing one or more trailing letters _sometimes_ works, sometimes it doesn't.
3) Trying to search the word without typing the letters in needed case (upper or lower)  _sometimes_ works, sometimes it doesn't.
4) Trying to search a phrase containing non-alphanumeric characters (e.g. parenthesis) leads to the non-alphanumeric characters being utterly ignored during search.

### Steps to reproduce the behavior

To reproduce 1: make a journal, pick a word from it, remove its first letter, and try to perform search.
To reproduce 4: make a journal, type something like `(abc)`, then try to search something like `!abc!`.

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

https://gist.github.com/ScumCoder/4795ce79add92df87286bd3a8ecd8e28 (it doesn't contain anything suspicious).

**Comment by user91756** [comment]
Running the same OS and having the same problem.  Searching tags produces no results.

**Comment by jianjwang** [comment]
Same to me, the search functionality was one of main reasons why I started using it, I hope it can be fixed ASAP, Many thanks!

**Comment by marklf** [comment]
Same here. Yeah, the search function makes most of this nice application. Thanks!
Rednotebook 2.4
Fedora 27

**Comment by mamaicas** [comment]
Same problem under Windows 10; Rednotebook 2.4
Thanks to user91756 "Downgrading to 2.3 fixed both problems for me" ... and for me.

I love this application, thanks for your work!

**Comment by khara50** [comment]
Seems version 2.4's search problem happens to everyone and simple solution is to downgrade to 2.3.
For Windows people, getting rednotebook-2.3.exe is easy.  For those (like me) using Linux, finding
rednotebook-2.3.deb or equivalent is possible?  What I did is getting rednotebook-2.3.tar.gz.
Unzip this tar ball and run the script 'run'.  That's all.  No need to install anything (of course you need python3).

**Comment by ScumCoder** [comment]
@jendrikseipp 
How much work would it take to implement both the old and the new (indexed) algorithms and add a setting to the "Preferences" window allowing to choose the needed one?

**Comment by jendrikseipp** [comment]
Maintaining two different searches requires too much work, unfortunately.

**Comment by ScumCoder** [comment]
Too bad.

For me that means that I am going to use the 2.3 version for undefined period of time.
That's OK, I would've even preferred to stay on 1.10.1 if the spellcheck didn't abruptly stop working.

With all due respect, my UX with 2.4 (and 2.3) was worse then with 1.10.1 in almost every regard - from the new database format which replaces newlines with `/n` and wraps long lines of text, which made using tools like `diff` utterly impossible; to the incomprehensible switch to using the browser for viewing the journal on Windows*.

* - I do not use Windows and thus I've barely used the Windows version, so I may have missed your plan. Maybe the Windows version has a way to switch back to properly viewing the journal in the RedNotebook itself, instead of launching the browser, but I haven't found it.

**Comment by mamaicas** [comment]
Hi,
If you use a index based in full words It should be possible to use wildcards like * or % to search for the begining/end of a word
Search of partial words is one of the main reasons I use this program. Best regards
    En domingo, 27 de mayo de 2018 21:49:22 CEST, Jendrik Seipp <notifications@github.com> escribió:  
 
 
Maintaining two different searches requires too much work, unfortunately.

**Comment by marklf** [comment]
＠jendrikseipp Thanks a lot for your great work for this application!

For those who use Chinese and other likewise, the search of 2.4 gives no result at all. What should we do with it? As far as I know there are quite some people from China and Japan are using it.

**Comment by jendrikseipp** [comment]
@marklf That's a very good point. It didn't occur to me that some languages don't use whitespace to separate words.

I guess the simplest solution here is to revert to the old version of the search feature. Probably there should be a configuration option for deactivating the search-as-you-type feature then. This feature can make typing search phrases take very long for very large journals.

**Comment by khara50** [comment]
Yes, it works for Japanese (non-spacing) text.

**Comment by marklf** [comment]
@jendrikseipp Thanks! It works for me with Fedora 28 in Chinese.

**Comment by jendrikseipp** [comment]
Thanks for testing! The changes have now been merged into the master branch and will be part of the next release.
