### ISSUE TITLE
Further statistics

### ISSUE THREAD

**Issue by PhlppKnst** [jendrikseipp/rednotebook#399]
Hi,
this is not an issue.
Is there a possibility to do more statistics with the hashtags .
Something like #guitar 10 min
and then having some window which shows a statistic where you can see the average time each day I practiced guitar, or how much guitar I played each day.
Is a feature like this planned?
Would a pull request with feature like this are welcome?

Best,
Philipp

**Comment by jendrikseipp** [comment]
Hi, while this is an interesting idea, it is quite specialized. RedNotebook tries to stay as simple as possible both interface- and code-wise.
