### ISSUE TITLE
Make dates with notes more distinct

### ISSUE THREAD

**Issue by johnblommers** [jendrikseipp/rednotebook#400]
### Versions 

RedNotebook version: **2.3**

Operating system and version: **mac OS 10.11.6 El Capitan**

### Expected behavior
Dates with notes should be very distinct, with a tasteful background behind the bolded numerals.

### Actual behavior
The bolded dates with notes are rather indistinct

### Steps to reproduce the behavior
Click on any date and type in a few words in the note pane. The bolded date in the calendar is not that distinct.

### Log output when reproducing behavior
This is an enhancement request and  there are no errors in the log about this. See the attached screenshot for a suggested way to highlight dates that have a note - a green circle for the 10th of June.
![datewithnote](https://user-images.githubusercontent.com/8484427/41214678-6bff75da-6d01-11e8-8266-c575fc89a0b1.png)

**Comment by jendrikseipp** [comment]
Good idea! Previously this wasn't possible due to limitations of the underlying GTK library, but the styles in GTK have become more customizable recently, so maybe this could be possible now.

**Comment by jendrikseipp** [comment]
You'll find the `Calendar` class in `rednotebook/gui/customwidgets.py`.

**Comment by thompson-vii** [comment]
`gtk.Calendar.mark_day` sets the edited date to bold. I checked the Calendar apis and did not find anything related to marking style. So yes, this requires a custom style.

**Comment by thompson-vii** [comment]
Having inspect the calendar widget with gtk inspector, I did not find any css styles that corresponds to the date thats being marked. Don't think this change is possible within pygtk.

**Comment by jendrikseipp** [comment]
Thanks for investigating! Closing this issue then.
