### ISSUE TITLE
Focus switches from search window to main text while typing

### ISSUE THREAD

**Issue by oosterwal** [jendrikseipp/rednotebook#401]
### Versions

RedNotebook version: 2.4

Operating system and version: Windows 7 Professional w/Service Pack 1

### Expected behavior

While typing in the search window the cursor focus should remain in the search window while the search term(s) are being entered.

### Actual behavior

Often, after clicking in the search window to enter a term, the first letter typed appears in the search window but the cursor focus then jumps to a seemingly random location in the main text entry window.
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/2210471/rednotebook.log)

### Steps to reproduce the behavior

1. Perform a search.
2. Select one of the dates in the result.
3. Double-click the term in the search window to highlight/over-write it and quickly type a new term.

You should see a few of the typed letters in the search window and the remaining letters appearing in a seemingly random location of the main text window for a seemingly random date file.

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

**Comment by jendrikseipp** [comment]
Thanks for the report! I could reproduce the error on my Ubuntu 16.04 system.

**Comment by jendrikseipp** [comment]
This still happens in version 2.6.1.

**Comment by Shardle** [comment]
Platform: Linux Mint Mate

I've has this issue for months with various versions of rednotebook. I've just updated to 2.7 and it is still happening. Often search works fine but quite often I'll start typing in search and find that after the first character, the cursor has jumped into the main window and I'm typing there, damaging what was previously written. Typically that would happen when I'd done one search and used it to go back to an earlier date and then try another search. There is no entry in the log when this occurs. It is a serious problem and has caused me to spend a good bit of time looking for alternatives.

**Comment by Shardle** [comment]
am on 2.7.1 now . . . . early indications are good . . .  can't get the issue to appear now.
I was not able to find another note taking program which suits me and use Rednotebook a lot so this is great news.
Thankyou very much.
