### ISSUE TITLE
Latex/Mathjax not working when diacritics present

### ISSUE THREAD

**Issue by carnendil** [jendrikseipp/rednotebook#408]
### Versions

RedNotebook version : 2.6.1 and a few earlier versions

Operating system and version: Ubuntu 16.04

### Expected behavior

Mathjax rendering LaTeX normally.

### Actual behavior

Whenever there is a letter with accents or diacritics (in Spanish, the vowels: á, é, í, ó, ú, and ü; and the letter ñ), LaTeX will not be rendered properly, showing all code in plain text.

This seems to be related somehow to issue #331 .

### Steps to reproduce the behavior
 1. On a blank page, type:
    `\(\LaTeX\)`
 2. Preview the page, it should render properly
![captura de pantalla de 2018-10-04 17-40-00](https://user-images.githubusercontent.com/43866161/46508835-9f1d8c80-c7fc-11e8-9e44-cc616a824540.png)

 3. Edit the page to:
    `\(\LaTeX\) en español`
 4. When previewing the page, "LaTeX" is not rendered by Mathjax.
![captura de pantalla de 2018-10-04 17-40-14](https://user-images.githubusercontent.com/43866161/46508853-b65c7a00-c7fc-11e8-8e0b-c6ee6d171a8e.png)

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

After both tests, the log adds two instances with the following (one per test):
``(timestamp) DEBUG    Add mathjax code: True``

**Comment by jendrikseipp** [comment]
This is issue seems to be fixed in the latest RedNotebook version. Feel free to reopen if it isn't.
