### ISSUE TITLE
Create Flatpak app for RedNotebook

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [jendrikseipp/rednotebook#409]
Please do consider making a snap for RedNotebook. The makers of my distro are showing no interest in updating this amazing software.

**Comment by Mikaela** [comment]
* https://docs.snapcraft.io/build-snaps/python

Snap is one of the attempts of being universal package manager across Linux distributions.

However as Snapd is tightly tied to Ubuntu supporting only one repository at a time, I personally prefer Flatpak for graphical apps. 

* http://docs.flatpak.org/en/latest/first-build.html

You may also be interested in [Adoption of Flatpak vs Snap (2018 edition)](https://kamikazow.wordpress.com/2018/06/08/adoption-of-flatpak-vs-snap-2018-edition/).

**Comment by jendrikseipp** [comment]
@iknownothingaboutcomputers What is your distro? 

I agree with @Mikaela that Flatpak sounds like the better alternative at the moment. Would you be interested in helping to work on a Flatpak version?

**Comment by Mikaela** [comment]
Sorry, I don't have any coding skills and haven't ever packed anything, so I am not able to be much help. I am only thinking of starting rednotebook and started watching the repository as this issue tracker didn't seem very high activity.

**Comment by jendrikseipp** [comment]
No worries. Maybe someone else can work on this. Let me update the issue title.

**Comment by scx** [comment]
@Mikaela 
@jendrikseipp 

I created a flatpak package for RedNotebook. I am in the process of submitting it to the Flathub repo.
https://github.com/flathub/flathub/pull/766

See also:
https://github.com/jendrikseipp/rednotebook/issues/419
