### ISSUE TITLE
Improve debian/control file

### ISSUE THREAD

**Issue by slavkoja** [jendrikseipp/rednotebook#410]
I recently build deb package from latest (2.6.1) tarball. I noticed that here is working debian directory settings. I (and ``lintian``) have one suggestion to reformat package description as this (without change phrasing):
```
Description: Modern desktop diary and personal journaling tool
 It lets you format, tag and search your entries. You can also add pictures,
 links and customisable templates, spell check your notes, and export to plain
 text, HTML, LaTeX or PDF.
```
It is because the first line of the Description filed have to be short package description, without full stop.

regards

**Comment by jendrikseipp** [comment]
Thanks for bringing this up!
