### ISSUE TITLE
Error when click URLs in the application, eg. on the ABOUT dialog or Credits

### ISSUE THREAD

**Issue by mzebitz** [jendrikseipp/rednotebook#411]
### Versions

RedNotebook version (make sure you have the latest version): 2.6.1

Operating system and version: Windows 7 64bit

### Expected behavior
Open Default browser with selected url when click on them

### Actual behavior
Error message on click

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

**Comment by mzebitz** [comment]
Here are the screenshots of the errors:
![2018-11-06_063502 rvnd2373_001_](https://user-images.githubusercontent.com/8188860/48044979-c2867f00-e18e-11e8-9915-d20264c47680.png)
![2018-11-06_064011 rvnd2373_002_](https://user-images.githubusercontent.com/8188860/48045013-da5e0300-e18e-11e8-9681-49dd4f62062d.png)

**Comment by jendrikseipp** [comment]
Thanks for the report! I was able to confirm the problem on Windows. Interestingly, running RedNotebook under Wine showed a different error ("Could not show link - No application is registered as handling this file"), but fixing this for Wine is not that important.

For Windows, https://github.com/mypaint/mypaint/issues/551 gave the right clue, we need the gspawn-win32-helper.exe to reside next to rednotebook.exe. I will include the exe in the installer for the next RedNotebook release that I'll make shortly. Can you confirm that RedNotebook version 2.7 fixes this issue?
