### ISSUE TITLE
Support word and tag clouds on Windows again

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#415]
RedNotebook had to remove the word and tag clouds in the Windows version since WebkitGtk doesn't support Windows anymore. The plan is to use CEF Python to implement this functionality again.

**Comment by CPC67128** [comment]
Thank you for the information. I was writing an issue when the GitHub search show me your comment which answers why I don't see Cloud after upgrading to 2.8. I will be patient then. Thanks for all your work.

**Comment by crogonint** [comment]
New user here. Is this permanently broken, or did it just not get ticked off? I've been digging around a bit, it looks like you intended to fix it two years ago, but I can't find any other notes on the issue. The download page still has version 1.15 and 2.20 offered for download. I'm guessing that 2.7 and 2.8 are actually 2.07 and 2.08, and are older than 2.20, but I'm already scratching my head, so I don't want to assume and downlaod the wrong one.

As a new user, I'd like to test whichever one has the most working featurs. Which one would you recommend?

**Comment by jendrikseipp** [comment]
The word cloud is still not implemented for Windows. I recommend using the latest version since word clouds are not terribly important in my opinion. The versions are forwards and backwards compatible though, so you can try both versions and decide what works best for you.

You're right, for versioning numbers we have 2.07 = 2.7, etc.

**Comment by crogonint** [comment]
Very good, thanks for the quick response!

**Comment by rmpf** [comment]
Hi. Just as a follow up i would like to know if windows users still have no access to word cloud???

**Comment by jendrikseipp** [comment]
That's correct. Unfortunately, there's no browser widget anymore on Windows for the underlying GTK toolkit. I tried to make it work with CEF Python, but this is also unsupported.

If you want to have the word cloud, you can use an older version of RedNotebook. The storage format is compatible between all RedNotebook versions.
