### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by scx** [jendrikseipp/rednotebook#419]
I created a flatpak package for RedNotebook.
https://github.com/scx/rednotebook-flatpak

I am in the process of submitting it to the Flathub repo.
https://github.com/flathub/flathub/pull/766
https://github.com/scx/flathub/tree/io.sourceforge.RedNotebook

It would be nice if the author decided to participate in the further development of this flatpak package.

**Comment by jendrikseipp** [comment]
That's great news. Thank you very much for your work! Apart from #420, do you need my help somewhere?

**Comment by scx** [comment]
I will try to take care of the flatpak package as much as I can. All comments are welcome. I want to make sure that everything works as it should.

**Comment by jendrikseipp** [comment]
The release scripts now automatically push each new version to the flathub repo. Thanks again for your work!
