### ISSUE TITLE
Emojis break the YAML parser on Windows

### ISSUE THREAD

**Issue by ScumCoder** [jendrikseipp/rednotebook#423]
### Versions

RedNotebook version (make sure you have the latest version): 1.15 (I can't use the latest version because I need proper preview and tag clouds)

Operating system and version: Win7 x64 SP1

### Expected behavior

Database created by RedNotebook on Linux can be imported into RedNotebook on Windows by a drop-in replacement of the `data` folder.

### Actual behavior

Upon launch, RedNotebook crashes with `ValueError: unichr() arg not in range(0x10000) (narrow Python build)`.

### Steps to reproduce the behavior

Insert an emoji into the database, e.g. using Linux version or just by opening the YAML file in Notepad and inserting `\U0001F609`.

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/2705263/rednotebook.log)

**Comment by jendrikseipp** [comment]
Thanks for the report. I recently updated the underlying stack and built a new executable for Windows. The result is not quite finished, but I'm interested in whether it solves your issue. Also, it should print more error logs. Could you please download the tarball from https://ci.appveyor.com/api/buildjobs/cndx9eg6894m15ma/artifacts/rednotebook.tar.gz, extract it (with 7zip) and start the rednotebook.exe program?

**Comment by ScumCoder** [comment]
I tested this version and it does not crash while loading files which contain emojis. `rednotebook.log` does not contain any errors.

**Comment by jendrikseipp** [comment]
Thanks for testing this!
