### ISSUE TITLE
I can not add images or pictures of any format in the journal.

### ISSUE THREAD

**Issue by marcobaturan** [jendrikseipp/rednotebook#424]
### Versions

RedNotebook version (make sure you have the latest version):2.8

Operating system and version: Ubuntu 18.04

### Log output when reproducing behavior: I can not found the error log of application

Please paste contents from $HOME/.rednotebook/rednotebook.log,
 1 2018-12-26 00:49:28,239 INFO     Writing log to file "/home/marco/.rednoteboo
 2 2018-12-26 00:49:28,240 INFO     System encoding: utf-8                      
 3 2018-12-26 00:49:28,240 INFO     Language code: es_ES                        
 4 2018-12-26 00:49:28,678 INFO     Running in portable mode: False             
 5 2018-12-26 00:49:28,678 INFO     First Start: False                          
 6 2018-12-26 00:49:28,678 INFO     RedNotebook version: 2.8                    
 7 2018-12-26 00:49:28,725 INFO     System info: machine: x86_64, platform: Linu
 8 2018-12-26 00:49:29,333 DEBUG    Default font: Ubuntu 11                     
 9 2018-12-26 00:49:29,333 DEBUG    Default size: 11.0                          
10 2018-12-26 00:49:29,657 INFO     Cloud ignore list: ['filter', 'these', 'comm
11 2018-12-26 00:49:29,658 INFO     Cloud include list: ['tele', 'spam', 'trabaj
12 2018-12-26 00:49:29,658 DEBUG    Start compiling regexes                     
13 2018-12-26 00:49:29,661 DEBUG    Finished                                    
14 2018-12-26 00:49:29,716 DEBUG    Tray icon visible: False                    
15 2018-12-26 00:49:29,718 INFO     Opening journal at '/home/marco/.rednotebook
16 2018-12-26 00:49:29,718 DEBUG    Starting to load files in dir "/home/marco/.
17 2018-12-26 00:49:29,719 DEBUG    Loading file "/home/marco/.rednotebook/data/
18 2018-12-26 00:49:29,721 DEBUG    Finished loading files in dir "/home/marco/.
19 2018-12-26 00:49:29,971 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Si
20 2018-12-26 00:49:29,972 DEBUG    Start took 1.293947696685791 seconds        
21 2018-12-26 00:49:29,972 DEBUG    Trying to enter the gtk main loop           
22 2018-12-26 00:49:30,228 DEBUG    Update the cloud                            
rednotebook.log (15,35) Unknown unix     Alt-g: show bindings, CtrlG: open help 
Copied selection                                                                

where $HOME is usually C:\Users\<username> on Windows.

**Comment by jendrikseipp** [comment]
Could you provide some screenshots for your problem, please?

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
