### ISSUE TITLE
Windows 10 Rednotebook 2.8 won't start

### ISSUE THREAD

**Issue by erezwa** [jendrikseipp/rednotebook#427]
After new and first installation on Win10, RedNotebook won't start.
I get the following massage

**Can someone explain, how do I can make this version working on windows 10
Thanks.**

Fatal Error!
Failed to execute script journal

![image 1](https://user-images.githubusercontent.com/46652633/51088135-e5bc4480-1764-11e9-95ec-cc7352d02e08.jpg)

**Comment by jendrikseipp** [comment]
We recently discussed this here: https://answers.launchpad.net/rednotebook/+question/674672

The gist: you can download a beta version that works on newer Windows versions here: https://www.dropbox.com/s/wa4o49pquma8bko/rednotebook-2.9b.exe?dl=1

I'd be interested to hear if everything works in the beta.

Make sure that your antivirus software doesn't interfere with the installation (as was reported before).

**Comment by ursjoss** [comment]
Solved in 2.9 IMHO. Thanks!

**Comment by jendrikseipp** [comment]
Thanks for testing!
