### ISSUE TITLE
Don't query DVD drive during startup

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#433]
### Versions

RedNotebook version: 1.1.2, 2.9, 2.9.1, 2.11

Operating system and version: Windows Vista Home Premium SP 2, Windows 7 64 bit, Windows 7 with SP1

https://bugs.launchpad.net/rednotebook/+bug/717217:
On start-up, I receive a pop-up error, "There is no disk in drive \Device\Harddisk1\DR1"
After clicking Continue or the red X multiple times the program runs normally, however the pop-up is impossible to close.

https://answers.launchpad.net/rednotebook/+question/679601:
On launch an "error" popup occurs with the following information

```
Rednotebook.exe
There is no disk in the drive. Please insert a disk into drive \Device\Harddisk2\DR2.
```

The popup can be closed and the application continues OK.
Uninstalled and reinstalled, error continues.

https://answers.launchpad.net/rednotebook/+question/679518:
Since version 2.9.0, every time I start RedNotebook it queries my DVD-ROM drive (F:) and comes back with a "No disc in Drive F:" error, forcing me to either click Cancel about 10 times, or insert a disc in the drive.

### Log output when reproducing behavior
Nothing out of the ordinary shows up in the logs.

**Comment by jendrikseipp** [comment]
Since Windows 7 will only be supported until January 2020 (IIRC), it would be interesting to know whether you see the same error on Windows 10.

**Comment by jendrikseipp** [comment]
Also, have you tried googling for the problem?

**Comment by Zaphod2012** [comment]
Whatever updates you made to the 2.11.0 release have stopped this behavior for me - The app is running as normal again :)

**Comment by jendrikseipp** [comment]
Closing this for now. Feel free to reopen if the error appears again.
