### ISSUE TITLE
Searching common words

### ISSUE THREAD

**Issue by alexanderlindstrom** [jendrikseipp/rednotebook#434]
### Versions

RedNotebook version (make sure you have the latest version): 2.11

Operating system and version: Linux Mint 19.1

### Expected behavior
Searching for a word which is common it is expected for the search result to show all instances of that word.
### Actual behavior
Only one instance per day show up, I believe it is the first instance that day.
### Steps to reproduce the behavior
- On the same day: Write two text which contains one specific word.
- Search that word.
### Log output when reproducing behavior
-

**Comment by jendrikseipp** [comment]
This is the desired behaviour. Once you click on the day that contains the word, all instances of the word are highlighted.
