### ISSUE TITLE
Crash after exiting template mode

### ISSUE THREAD

**Issue by atrooper** [jendrikseipp/rednotebook#435]
### Versions

RNB v2.11

Operating system and version: Win 10 Pro v1809
RNB data files are located on a network file share with "available off line selected". (Makes a copy on the local hardware synchronized to the network share)

### Expected behavior
Add a template without crashing
When the "Spell Check" option is selected.

### Actual behavior
Spell Check option is selected
RNB crashes after exiting template mode followed by pressing the "del" or "back" keys.

### Steps to reproduce the behavior
Check the "Spell Check" box. (was already checked after RNB restart)
Select Template and any template name then "Save and Insert" or "Close"
- Pressing the delete or back keys causes RNB to close without saving.

Alternatively Select Journal->Save then delete or back keys still will cause RNB to close but journal entry is saved.
After save, followed by crash behavior, subsequent restart then delete or back keys work as expected.
- This behavior is not present if the "Spell Check" box is not checked.

### Log output when reproducing behavior
CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "C:\repo\rednotebook\external\spellcheck.py", line 596, in _range_delete
  File "C:\repo\rednotebook\external\spellcheck.py", line 445, in check_range
  File "C:\repo\rednotebook\external\spellcheck.py", line 623, in _check_word
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by jendrikseipp** [comment]
Thanks for the report. This should be fixed in RedNotebook 2.11.1. Can you confirm that?
