### ISSUE TITLE
Is there a dark theme or how can i set the background to be black

### ISSUE THREAD

**Issue by zhangyw49** [jendrikseipp/rednotebook#438]
### Versions

RedNotebook version (make sure you have the latest version):

Operating system and version:

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by DavBE** [comment]
I would love a dark theme !

**Comment by Bestulo** [comment]
Hmm, I can't find any way to turn the background dark. There's too much contrast and it's not comfortable.

![image](https://user-images.githubusercontent.com/23301025/68549417-03325d00-03ce-11ea-801f-0df8c9695389.png)

**Comment by jendrikseipp** [comment]
We're currently debating making the preview style configurable in #455 . Is the edit mode background dark?

**Comment by Bestulo** [comment]
Yes, it is! The text cloud is also white.

>

**Comment by oughter** [comment]
I suddenly got a dark background when I upgraded my OS recently. I didn't change any OS or RedNotebook settings (v2.11.1) -- maybe the app suddenly started honoring my existing OS Adwaita-dark theme setting for applications.

![Screenshot from 2019-11-17 10-29-58](https://user-images.githubusercontent.com/18747026/69009730-43da2b00-0926-11ea-808d-7fa030f686a0.png)

![Screenshot from 2019-11-17 10-30-14](https://user-images.githubusercontent.com/18747026/69009731-46d51b80-0926-11ea-9ae3-fc3df301c569.png)

I mostly like the way it looks on my system. The contrast for the Tags and Word cloud sections as well as links in content is too low to read easily, but having a dark background for the preview mode especially is nice.

**Comment by jendrikseipp** [comment]
Very interesting. Thanks for reporting this!

**Comment by jendrikseipp** [comment]
Now the cloud view should respect the dark preference as well.

**Comment by jendrikseipp** [comment]
@oughter can you confirm that the cloud panel now also supports dark mode?

**Comment by oughter** [comment]
> @oughter can you confirm that the cloud panel now also supports dark mode?

Yes, it does. Thanks for the fix :+1:

**Comment by jendrikseipp** [comment]
Awesome :-)

**Comment by ankurash** [comment]
Is there a dark theme/mode for windows (10)?

**Comment by jendrikseipp** [comment]
> Is there a dark theme/mode for windows (10)?

Yes, you can use any GTK theme. You can use these instructions (replace Shoe by RedNotebook): https://github.com/shoes/shoes3/wiki/Changing-Gtk-theme-on-Windows

The relevant parts are 

> You copy a gtk3 compatible theme into your installed shoes - e.g: C:\Program Files (x86)\Shoes\share\themes and then you edit C:\Program Files (x86)\Shoes\etc\gtk-3.0\settings.ini to comment out it's current setting and add your own.

> For example, this theme FlatStudio - if you download that (tar.gz) and expand it you'll see there are 4 Themes FlatStudio, FlatStudioDark, FlatStudioLight, FlatStudioGray. Pick one of those folders (FlatStudio for example) and copy it into your installed Shoes share\themes folder. Then edit etc\gtk-3.0\settings.ini so it looks similar to this:

```
[Settings]
#gtk-theme-name=win32
gtk-theme-name=FlatStudio
```

> If settings.ini has nothing set (all commented out) it defaults to the Windows theme), if a gtk-theme-name is set but can't be found or used, then it defaults to a light brown ugly style (Raleigh, built in?)

Does it work for you?

**Comment by ankurash** [comment]
> > Is there a dark theme/mode for windows (10)?
> 
> Yes, you can use any GTK theme. You can use these instructions (replace Shoe by RedNotebook): https://github.com/shoes/shoes3/wiki/Changing-Gtk-theme-on-Windows
> 
> The relevant parts are
> 
> > You copy a gtk3 compatible theme into your installed shoes - e.g: C:\Program Files (x86)\Shoes\share\themes and then you edit C:\Program Files (x86)\Shoes\etc\gtk-3.0\settings.ini to comment out it's current setting and add your own.
> 
> > For example, this theme FlatStudio - if you download that (tar.gz) and expand it you'll see there are 4 Themes FlatStudio, FlatStudioDark, FlatStudioLight, FlatStudioGray. Pick one of those folders (FlatStudio for example) and copy it into your installed Shoes share\themes folder. Then edit etc\gtk-3.0\settings.ini so it looks similar to this:
> 
> ```
> [Settings]
> #gtk-theme-name=win32
> gtk-theme-name=FlatStudio
> ```
> 
> > If settings.ini has nothing set (all commented out) it defaults to the Windows theme), if a gtk-theme-name is set but can't be found or used, then it defaults to a light brown ugly style (Raleigh, built in?)
> 
> Does it work for you?

It worked. I was almost ready to dive in and contribute to add support for dark theme. 
Well, will have to find some other missing feature.

**Comment by jendrikseipp** [comment]
> Well, will have to find some other missing feature.

Sounds good :-) If you like, you could add the instructions for how to change the theme under Windows to the included help document.

**Comment by anta999** [comment]
What about dark theme for Win11 ?

**Comment by anta999** [comment]
> @anta999 Is it not working on Win11?

Yes sir
![RedNote](https://github.com/jendrikseipp/rednotebook/assets/48290431/8e6cc773-7105-49b4-9fc1-275de70be66d)

**Comment by anta999** [comment]
Sorry . Everything works great on win11 - didn't read the instructions above.

**Comment by eliblanco87** [comment]
The problem with dark themes is that highlight (when you search) is always a bright yellow color and the white text inside can't be read...
