### ISSUE TITLE
internal preview on Windows

### ISSUE THREAD

**Issue by mzebitz** [jendrikseipp/rednotebook#439]
### Versions

RedNotebook version (make sure you have the latest version): 2.8

Operating system and version: WIndows 7, 64bit
Microsoft Windows 7 Enterprise
Service Pack 1 , 6.1.7601
7601

### Expected behavior
I wish to keep the internal preview on windows, so .. suggestion is to add it as on option, internal or external preview

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by idle-code** [comment]
Have you tried newest version 2.11?
I believe it comes with internal preview only.

**Comment by jendrikseipp** [comment]
Thanks @idle-code!
