### ISSUE TITLE
Show tag panel if and only if journal contains old-style tags

### ISSUE THREAD

**Issue by trymeouteh** [jendrikseipp/rednotebook#440]
I just updated to 2.11.1 and I am unable to find a way to add a tag to an entry, or even be able to remove tags and modify tags. In 2.4 there was a panel to the right where you can edit the tags.

**Comment by trymeouteh** [comment]
I guess the option to show/hide the tags panel got removed in 2.5. Please add it setting back in the GUI.

**Comment by idle-code** [comment]
You are right.
For now you can set `showTagsPane` property in `~/.rednotebook/configuration.cfg` file to 1.

**Comment by idle-code** [comment]
@jendrikseipp has tags pane been depreciated in favor of hashtags? I have found [this](https://github.com/jendrikseipp/rednotebook/commit/2ef88a7c75e7cd53ea6c35c99f4652b9a90b14f6) commit which explicitly removed this feature.
Could you tag this issue appropriately?

**Comment by jendrikseipp** [comment]
Hi @idle-code, the tags pane is deprecated. Ideally, I think we should set showTagsPane to 1 if and only if the opened journal contains (non-hashtag) tags.

**Comment by trymeouteh** [comment]
I like using tags to add metadata to my posts. For example I always use two tags on each post which is the Entry tag which is the entry # in my journal, and the Location tag to tell me where I was in the post such as the city or country.

I hope this feature does not get fully removed from RedNotebook

**Comment by jendrikseipp** [comment]
I think the showTagsPane option is actually sufficient. Closing this issue.
