### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by daVe55w** [jendrikseipp/rednotebook#442]
v 2.11
Changing font to anything besides the default Sans font has no effect when switching from Edit to Preview mode.

**Comment by idle-code** [comment]
I cannot reproduce it on v2.11.1.
The trick is to use right font name - underneath, RedNotebook uses HTML for preview and the _Preview font_ name should be in form accepted by CSS [font-family](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) property.

**Comment by jendrikseipp** [comment]
Thanks @idle-code!
