### ISSUE TITLE
Cannot insert template without saving it

### ISSUE THREAD

**Issue by Rocketansky** [jendrikseipp/rednotebook#443]
### Versions

RedNotebook version (make sure you have the latest version): 2.11.1

Operating system and version: Win 10 1809

### Expected behavior
If I select a template I would expect that it is inserted.
### Actual behavior
If I select a template I get into the editing of the template and I have to use the button "Save and Insert". But I do not want to save!
### Steps to reproduce the behavior
1) Click on button template
2) Select one of the templates
### Log output when reproducing behavior
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/3448879/rednotebook.log)
Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
### Additional comment
Hovering over the template button shows the text "Click the arrow on the right for more options" but there is no arrow on the right.

**Comment by jendrikseipp** [comment]
I agree that this would be nice to have.

**Comment by jendrikseipp** [comment]
I thought about this again and believe that the current behaviour is more intuitive for users. Otherwise, users might change a template, insert it, but forget to save it.
