### ISSUE TITLE
Backup only 22 bytes

### ISSUE THREAD

**Issue by desdamona902** [jendrikseipp/rednotebook#445]
### Versions

RedNotebook version (make sure you have the latest version):
2.8

Operating system and version:
Windows 7 home premium
### Expected behavior
Backup file should be approximately 1M
### Actual behavior
22 bytes
### Steps to reproduce the behavior
Select Journal backup - Save

### Log output when reproducing behavior

[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/3505665/rednotebook.log)

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by jendrikseipp** [comment]
You probably only mixed up some paths or clicks. Journal->Save just saves the journal txt files, Journal->Backup stores them in a zip file.

**Comment by desdamona902** [comment]
I'm doing a Journal **Backup** and it's saving it to a zip file. Doesn't the log show that?

**Comment by desdamona902** [comment]
How do I get this reopened? The problem is not solved.

**Comment by jendrikseipp** [comment]
Can you open the zipfile? Which files are in the zipfile? Can you open them? Do they have content?

**Comment by desdamona902** [comment]
When I try to open the zip file, it says it is empty. Also, when I opened RedNotebook this morning, all my data is missing. Nothing. I had about nine years of data here. I have older backups, but didn't want to restore before hearing from you.

**Comment by desdamona902** [comment]
I decided to restore from a month ago. This worked, so I did a Journal>Backup and this worked, also. So I don't know what the original problem was ( even though I tried the backup multiple times).

**Comment by jendrikseipp** [comment]
Good to hear that you were able to recover! Feel free to reopen, when you find out what was responsible for this behaviour.
