### ISSUE TITLE
Export days with common tag

### ISSUE THREAD

**Issue by trendoman** [jendrikseipp/rednotebook#448]
### V. 1.15
Hi everyone, 

I know this is not yet in the latest version, so maybe it could be added later on? Please..

I click on a tag and have a filtered list of days containing that tag. I then go to Export, but can only export selected day, not all the days from my list. Perhaps, if there was another option - export a tag, - that would remove the need to manually export all days.

Thanks!

**Comment by jendrikseipp** [comment]
You can use "Filter days by tags" in the export dialog.
