### ISSUE TITLE
Feature  Request: notebook sync to "the cloud"

### ISSUE THREAD

**Issue by pkt-nspktr** [jendrikseipp/rednotebook#451]
### Versions

RedNotebook version (make sure you have the latest version): 2.11.1 (Downloaded source on 08 Oct 2019)

Operating system and version: GhostBSD 19.09 (FreeBSD 12.1-PRERELEASE GENERIC)

###  Feature Request

I would like to replicate the ability to save notes/notebooks to "the Cloud" a la MacOS' and iOS [Notes.app](https://en.wikipedia.org/wiki/Notes_(Apple)). I use FastMail.com as my mail provider and it offers the ability to sync Notes from the phone to the desktop and visa versa. I believe it uses an IMAP folder as a hack to accomplish this feature (though I have not found much documentation on the protocol used by Notes.app).

I'm not an Android user, but I know Google offers the Keep (keep.google.com) note application with Gmail accounts and I would guess that Android has a parallel app for syncing those notes. 

It would be convenient for RedNotebook to offer a standards-based method of syncing notes across multiple devices/service providers.

**Comment by NathanSalapat** [comment]
You can always save your journal directory in a synced folder on you computer. I use dropbox to accomplish this.  It should work with any service that lets you do a simple folder layout with text files.

**Comment by jendrikseipp** [comment]
Thanks, @NathanSalapat, that's correct.

**Comment by pkt-nspktr** [comment]
@NathanSalapat , @jendrikseipp, Thanks for the quick reply. I'm glad that Rednotebook has such a responsive community. 

What app do each of you use on your phone to edit notes in "a simple folder layout with text files?" As I mentioned, I used the included iPhone Notes.app to create/edit short notes which are synced via IMAP (as best as I can tell).  If I move to a synced folder layout over WebDAV or FTP, Notes.app would no longer meet my needs to sync notes between phone and desktop. 

Thanks for the recommendation of Dropbox, however, it does not support WebDAV or FTP[1] and it does not have a *BSD client[2]. I am looking to move away from macOS on the desktop for various reasons and have selected to use a *BSD desktop for other reasons.


[1] https://help.dropbox.com/installs-integrations/third-party/webdav-or-ftp
[2] https://help.dropbox.com/search-results#q=freebsd&t=HelpCenter&sort=relevancy

**Comment by NathanSalapat** [comment]
I actually just use Dropbox for backing up. I know the format of the data files is fairly simple so any text editor app should let you modify them. You just need to keep the formatting scheme in mind so you don't bork things.
