### ISSUE TITLE
Feature Request: Allow an image to link to a file

### ISSUE THREAD

**Issue by oughter** [jendrikseipp/rednotebook#453]
Per #243, using an image for a link to a URL should be supported, but using an image to link to a file that has been inserted into an entry would be a nice feature. An example use case would be to use a thumbnail image that when clicked would open a local video file.

**Comment by idle-code** [comment]
You can try using `[[/path/to/image.jpg] /path/to/file.mp4]` syntax.
Unfortunately image scalling (`?WIDTH`) is not supported for this use case yet.

**Comment by oughter** [comment]
Thank you, @idle-code. I had tried various permutations of that syntax with no luck before and thought it just wasn't supported, but I tried some more and finally found one that works.

For others who come across this later, here is what works on my system (I'm on v2.11.1 on Linux):

`[[""file:///path/to/image"".png] file:///path/to/video.mp4]`

Note the quotes around the image path but not the video path and the inclusion of the image file extension after the closing quotes.
