### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by tuxedotje** [jendrikseipp/rednotebook#454]
### Versions

RedNotebook version (make sure you have the latest version): 2.11.1-2

Operating system and version: Fedora 31

### Expected behavior
launch 
### Actual behavior
crash
### Steps to reproduce the behavior
launch
### Log output when reproducing behavior
$ rednotebook
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 11, in <module>
    import rednotebook.journal
  File "/usr/lib/python3.7/site-packages/rednotebook/journal.py", line 44, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace GtkSource not available for version 3.0

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
No such fil, new install.

**Comment by tuxedotje** [comment]
Fedora 31 beta  Gnome "Software" app does install Rednotebook without problems.

**Comment by idle-code** [comment]
How did you installed the RedNotebook?
It seems that gtksourceview-3.0 might be missing.

**Comment by tuxedotje** [comment]
install on Fedora 31 with help of dnf-system gives a crash.
install with help of app Software gives a slow rednotebook. App Software does not show dependencies

**Comment by jendrikseipp** [comment]
Could you please report this to the Fedora package maintainers?
