### ISSUE TITLE
User Experience Improvement Proposal

### ISSUE THREAD

**Issue by furusiyya** [jendrikseipp/rednotebook#463]
I found Red Note Book while searching for an open source alternative of [Laverna](https://github.com/Laverna/laverna). The main reason of my search is the user experience of Laverna which is not good at-least for me.
So when I started using Red note book, I really liked the calendar feature but the original pain is still there - user experience of Edit interface.
When I am writing, I want focus similar to paper which can by provided by **full screen view feature**. When user click on full screen view button, top menu bar and calendar view bar disappears and user is writing in the middle of the screen, similar to Medium / Google Doc writing experience.
In my view - If rednotebook provides Medium like writing experience, people would love this app.

**Comment by jendrikseipp** [comment]
Have you tried RedNotebook's full screen feature by pressing F11? I think it comes pretty close to what you're describing. What would you change?

**Comment by jendrikseipp** [comment]
Feel free to reopen if F11 is not enough for your use case.
