### ISSUE TITLE
Version 2.15 for Windows installation failure

### ISSUE THREAD

**Issue by netkhan** [jendrikseipp/rednotebook#465]
### Versions

Windows 2.15

Operating system and version:

### Expected behavior
2.14 had no issue in installation
### Actual behavior
2.15 for Windows
Exe file has been removed by McCafee during installation.
Windows 10 initially block because of unknown publisher.
### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by jendrikseipp** [comment]
Thanks for the info. This is a common problem of virus software and affects all software, not just RedNotebook.
