### ISSUE TITLE
Feature Request: Add a background color to indicate the current day

### ISSUE THREAD

**Issue by tommai78101** [jendrikseipp/rednotebook#466]
### Versions

RedNotebook version (make sure you have the latest version): 2.15

Operating system and version: Ubuntu 18.04 LTS

### Feature

Requesting to add a background color to indicate the current day. Just need to have a subtle hint of color to indicate the day.

For example, today is December 10, 2019. We can have the current day be indicated as such:

![](https://i.imgur.com/SeZIP0u.png)

**Comment by jendrikseipp** [comment]
That's a nice idea, but the calendar only allows one type of highlighting (bold), which we already use to mark edited days.

**Comment by tommai78101** [comment]
@jendrikseipp May I request that you add this to the list of things that will not be implemented in RedNotebook's TODO list? Thanks.

**Comment by jendrikseipp** [comment]
Good idea, done :-)
