### ISSUE TITLE
Feature Request: Add calendar preference to display weeks as starting on Mondays

### ISSUE THREAD

**Issue by oughter** [jendrikseipp/rednotebook#468]
If possible with the calendar utility, please add the ability to configure the calendar to display weeks as starting on Mondays. This is a common option for applications that include calendars, and because of that for users who have all of their calendars configured to display Monday as the first day of the week, encountering one that starts the week on a different day can be disorienting.

**Comment by jendrikseipp** [comment]
You can change this setting globally for all applications: https://askubuntu.com/questions/6016/how-to-set-monday-as-the-first-day-of-the-week-in-gnome-calendar-applet Feel free to reopen if this doesn't work for you.
