### ISSUE TITLE
array.tostring was removed to use tobytes in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [jendrikseipp/rednotebook#470]
https://bugzilla.redhat.com/show_bug.cgi?id=1793161a

https://github.com/jendrikseipp/rednotebook/blob/80d6e151b3a289a4bede512cd0b55470a8d5a88a/rednotebook/external/msgfmt.py#L90

**Comment by jendrikseipp** [comment]
Thanks for the report!
