### ISSUE TITLE
Trojan:Win32/Occamy.B

### ISSUE THREAD

**Issue by danchay** [jendrikseipp/rednotebook#471]
### Versions

RedNotebook version (make sure you have the latest version):
rednotebook-2.16.exe

Operating system and version:
Windows 10 Pro Version 1903

### Actual behavior
Security scan on rednotebook-2.16.exe tells me it's contaminated with "Trojan:Win32/Occamy.B", a "severe" threat. Running the same scan on rednotebook-2.15.exe identifies no threats.

**Comment by jendrikseipp** [comment]
Thanks for the info. Unfortunately, false positives like this are a common problem of virus software and they affect all software, not just RedNotebook.

**Comment by danchay** [comment]
Well, how do I know it's a "false positive?"

**Comment by jendrikseipp** [comment]
Unfortunately, that's not so easy. However, all the code is open source, so you could inspect it, if you like.
