### ISSUE TITLE
Trojan:Win32/Occamy.B found in 2.16 by Windows defender

### ISSUE THREAD

**Issue by joepbeijnsberger** [jendrikseipp/rednotebook#472]
### Versions

RedNotebook version 2.16

Operating system and version: Windows 10 1909

### Expected behavior
Startup

### Actual behavior
Blocked by Windows defender. It finds Trojan:Win32/Occamy.B in version 2.16.
### Steps to reproduce the behavior
Install release 2.16 in Windows 10 with Windows defender active

### Log output when reproducing behavior
Not available

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

Workaround now is to install version 2.15.

**Comment by jendrikseipp** [comment]
Thanks for the info. Unfortunately, false positives like this are a common problem of virus software and they affect all software, not just RedNotebook.

**Comment by graphixillusion** [comment]
It seems that 2.17 has several false positives around:

https://www.virustotal.com/gui/file/13219950f3446e19c4d777c403d2cf34d0cf940211a9db54ce7f2d4b95edca31/detection

18/69 on VT.

**Comment by jendrikseipp** [comment]
This is a common problem for programs packaged with PyInstaller, see https://github.com/pyinstaller/pyinstaller/issues/4633#issuecomment-575537881.
