### ISSUE TITLE
Trojans included.

### ISSUE THREAD

**Issue by danchay** [jendrikseipp/rednotebook#476]
### Versions
2.16, 2.17
RedNotebook version (make sure you have the latest version):

"False positive?" At a minimum, it seems like a bug. Otherwise, worse. Dang. I'm forced to remove it.
The affected files seem to be RedNotebook.Ink, and in 2.17, rednotebook-2.17.3xe and rednotebook.exe.

Operating system and version:
Windows 10

### Actual behavior
Windows Defender returns the following:

v2.16
Threat detected: Trojan: Win32/Occamy.B
Alert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

v2.17
Threat detected: Trojan:Win32/Detplock
Alert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker

**Comment by jendrikseipp** [comment]
Duplicate of #472
