### ISSUE TITLE
Support markdown checkbox.

### ISSUE THREAD

**Issue by roachsinai** [jendrikseipp/rednotebook#479]
### Versions

RedNotebook version: 2-17.1

Operating system and version:Manjaro 19.0.1

### Expected behavior

support Markdown checkbox! 

- [ ] this

and

- [x] this

### Actual behavior

![image](https://user-images.githubusercontent.com/9500049/75638353-75bd9600-5c66-11ea-81e1-97453de5e02a.png)

**Comment by vlisivka** [comment]
x is the letter, so it will confuse spell checker and pollute tag cloud. Moreover, x can be confused with ☒.

It's better to support following notation:

* [ ]  TODO
* [+] Ok
* [-] Fail

And render them as ☐, ☑, and ☒.

* ☐ TODO
* ☑ OK
* ☒ Fail

**Comment by jendrikseipp** [comment]
This issue will be automatically fixed if we add Markdown support in #560.
