### ISSUE TITLE
Outdated testimonials

### ISSUE THREAD

**Issue by forteller** [jendrikseipp/rednotebook#480]
Hi. Just wanted to let you know that the Testimonial page seems very outdated. Links to articles comparing RedNotebook to other applications from 2010 is probably not relevant for anyone any more, and the video reviewing version 1.1.6 is just giving people a very wrong impression since it is so old. There are other, newer videos, like this one: https://invidio.us/watch?v=L-mlw4GJKUQ

Hope you will be able to update the page, or if not I think I would recommend that you delete it, so you won't give the impression that the product is abandoned.

Thanks for a great product and your great work! :)

**Comment by jendrikseipp** [comment]
Thanks for the tip! I took the path that involves the least amount of work and deleted the testimonials for now :-)
