### ISSUE TITLE
The program does not start in Windows 10

### ISSUE THREAD

**Issue by budhochat** [jendrikseipp/rednotebook#481]
### Versions

RedNotebook version (make sure you have the latest version): 2.18

Operating system and version: Windows 10 pro

### Expected behavior: 
Program opens after installing

### Actual behavior: 
The program does not starts after installation. Gives the message "Failed to execute script journal"
Tried with antivirus paused but same result.
Tried other versions of rednotebook but same results.

### Steps to reproduce the behavior:
Whenever tries to open the app

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

There is no rednotebook.log file.

**Comment by jendrikseipp** [comment]
Can you please try to open cmd.exe and execute `C:\Programs\RedNotebook\rednotebook.exe`? Is there any output?

**Comment by budhochat** [comment]
On executing this command: "C:\Program Files (x86)\RedNotebook\rednotebook.exe"
No output in the cmd prompt.
Same popup window appears:  
"Fatal Error Detected. 
Failed to execute script journal"

**Comment by jendrikseipp** [comment]
Thanks for testing this! Unfortunately, this means there's nothing much to act upon. I'm planning to upgrade the program that creates the executable which could fix the error, but this will take some time.

**Comment by budhochat** [comment]
Thanks.
Will check out the upgrade

**Comment by jendrikseipp** [comment]
Here is my attempt at upgrading the stack: #478 Unfortunately, the app crashes and I don't know how to debug it.

**Comment by budhochat** [comment]
Thanks for the effort.
Let me know if I can help with some testing.

**Comment by jendrikseipp** [comment]
#478 has been merged now. Does the latest RedNotebook version open correctly for you now?

**Comment by jendrikseipp** [comment]
Closing this issue for now, feel free to reopen if the problem persists.
