### ISSUE TITLE
With multiple links to other dates on one line, only the last link will work

### ISSUE THREAD

**Issue by Chips-86** [jendrikseipp/rednotebook#483]
### Versions

RedNotebook version (make sure you have the latest version): 2.18

Operating system and version: Ubuntu 16.04 LTS

### Expected behavior
Presumably, every link to another date on a single line should work, eg:
[Last Time 2020-02-02] - Now - [Next Time 2020-05-12]
when in Preview, one link links to 2020-02-02 and the other to 2020-05-12

### Actual behavior
When in Preview "Last Time" doesn't work but "Next Time" does.

### Steps to reproduce the behavior
paste this:
[Last Time 2020-02-02] - Now - [Next Time 2020-05-12]
and see if both links work.

### Log output when reproducing behavior
for the 2020-05-12 link:
2020-04-12 08:33:33,252 INFO     Clicked URI "file:///#2020-05-12"
but nothing for the 2020-02-02 link.

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by Chips-86** [comment]
Issue closed. Need # before all date entries, eg:
[Last Time #2020-02-02] - Now - [Next Time #2020-05-12]

**Comment by jendrikseipp** [comment]
I can confirm that for `[Last Time 2020-02-02] - Now - [Next Time 2020-05-12]` only the second link works. @idle-code, do you want to tackle this?

**Comment by Chips-86** [comment]
> I can confirm that for `[Last Time 2020-02-02] - Now - [Next Time 2020-05-12]` only the second link works. @idle-code, do you want to tackle this?

jendrikseipp - my apologies for starting this. I should have RTFM. According to your docs, dates need a # in front of them. I wasn't using the #. The issue is raised in error because it's not an issue.

**Comment by jendrikseipp** [comment]
Ah, I forgot that we added the hashtag to the date format. Thanks for clarifying!
