### ISSUE TITLE
Word clouds panel does not follow newly selected GNOME desktop theme until app restart

### ISSUE THREAD

**Issue by fbrnb** [jendrikseipp/rednotebook#485]
### Versions
RedNotebook 2.18

Operating system and version:
Fedora 31

### Expected behavior
RedNotebook restart should not be required so that the word clouds panel takes the theme in use.

### Actual behavior
Change between standard Adwaita and Adwait-dark GNOME desktop theme need a RedNotebook restart so that the word cloud panel takes the theme in use.

### Steps to reproduce the behavior
1. Start RedNotebook
2. Change GNOME deskop theme from standard Adwaita to Adwaita-dark.
3. RedNotebook 2.18 takes the native OS's dark interface for its elements, but for the word clouds panel and should be restarted to fully follow the newly selected theme.

**Comment by jendrikseipp** [comment]
This should be fixed in the development version now. Thanks for the report!
