### ISSUE TITLE
HTML export is "dark" when using Adwaita-dark GNOME desktop theme

### ISSUE THREAD

**Issue by fbrnb** [jendrikseipp/rednotebook#486]
### Versions
RedNotebook 2.18

Operating system and version:
Fedora 31

### Expected behavior
AMHO, RedNotebook HTML export should be desktop theme agnostic in order to follow proper HTML display and then print to PDF file.

### Actual behavior
RedNotebook follow Adwaita-dark GNOME desktop theme for its display (which is great - see: #474 and #438) but this desktop theme is also used when exporting to HTML which cause my problem.

### Used workaround
With Adwaita-dark GNOME desktop theme selected as the default one, a workaround is to :

1. select standard Adwaita GNOME desktop theme
2. [re]start RedNotebook (if the desktop theme change was made while running RedNotebook a restart is required in order to get the export assistant to follow the newly selected theme)
3. export to HTML
4. revert to Adwaita-dark GNOME desktop theme 
5. restart RedNotebook in order to get it fully follow the desktop theme for its display (see #485)

**Comment by jendrikseipp** [comment]
Good catch, thanks for the report! This should definitely be fixed. Can you program in Python and would like to submit a fix by any chance?

**Comment by fbrnb** [comment]
Unfortunately, I am unable to do so.

**Comment by jendrikseipp** [comment]
No worries :-)
