### ISSUE TITLE
Feature request: Pandoc support

### ISSUE THREAD

**Issue by sat3ll** [jendrikseipp/rednotebook#488]
Currently, rednotebook uses txt2tags to parse the markup. Allowing Pandoc to be used will enable users to use other markup languages (some with extra features compared to what txt2tags uses) and pandoc plugins/filters to preprocess certain parts of the text.

**Comment by jendrikseipp** [comment]
While this is an interesting idea, it's out of scope for RedNotebook. However, I'm thinking about adding Markdown support.
