### ISSUE TITLE
Edit mode shows nothing after upgrade to ver 2.19. Preview mode OK.

### ISSUE THREAD

**Issue by datacurata** [jendrikseipp/rednotebook#489]
### Versions

RedNotebook version (make sure you have the latest version): 2.19

Operating system and version:   Linux Mint 19.3 / Cinnamon v.4.4.8

### Expected behavior
1. When I start Red Notebook it should start in Edit mode and allow me to view any entries for the selected day in edit mode. 
2. I should be able to select and change text as needed.
3. I should be able to add templates and amend the text as appropriate.
4. I should not have to change to Preview mode to see the text entries. 

### Actual behavior
1. Red Notebook starts in edit mode as expected. However, no text is displayed for any selected day when viewing in edit mode.
2. I cannot see any text to select or change.
3. I can add a template but cannot make changes as I cannot see it in edit mode.
4. I do have to change to Preview mode to see text and verify any entries or template additions.

### Steps to reproduce the behaviour
Open Red Notebook .
Change to Edit mode.
Try writing text.
Add a template.
Try to amend that template in edit mode.

### Log output when reproducing behaviour
Log is attached.
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/4583238/rednotebook.log)
![Screenshot from 2020-05-05 edit-mode](https://user-images.githubusercontent.com/46908181/81110568-9c70a500-8f13-11ea-937f-2b8d3bdd14c6.png)
![Screenshot from 2020-05-05 preview-mode](https://user-images.githubusercontent.com/46908181/81110570-9d093b80-8f13-11ea-88b6-41a2911a540b.png)

Please paste contents from $HOME/.rednotebook/rednotebook.log,
see above.

**Comment by jendrikseipp** [comment]
Thanks for the detailed report! Did edit mode display the text in version 2.18, or what was the last version that worked for you? If you start RedNotebook from the commandline, is there any additional output compared to the logfile?

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
