### ISSUE TITLE
JPEG images not previewed correctly

### ISSUE THREAD

**Issue by CSChisholm** [jendrikseipp/rednotebook#490]
### Versions

RedNotebook version (make sure you have the latest version): 2.19

Operating system and version: Linux Mint 19.3 Cinnamon 4.4.8 with Kernel 5.3.0-51-generic x86_64

### Expected behavior

Previewer displays linked image.

### Actual behavior

When linking a .jpg file of 3072x4096 pixels the left edge is rendered incorrectly and the image is cut off vertically in the previewer both with and without scaling. In the html export the image is rendered normally in the browser.

### Steps to reproduce the behavior

Insert .jpg image in edit mode and then click preview.

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/4586535/rednotebook.log)

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
