### ISSUE TITLE
Remote servers are not found when trying to open or save a notebook

### ISSUE THREAD

**Issue by CSChisholm** [jendrikseipp/rednotebook#491]
### Versions

RedNotebook version (make sure you have the latest version): 2.19

Operating system and version: Linux Mint 19.3 Cinnamon 4.4.8

### Expected behavior

When opening or saving a notebook (or creating a new notebook) one should be able to navigate to go to Other Locations and connect to a server as one can do in Nemo.

### Actual behavior

smb and sftp protocols do not appear to be supported and network drives are not found regardless of whether or not the server has already been mounted outside of RedNotebook

### Steps to reproduce the behavior

Enter the directory selection dialog form RedNotebook and navigate to other locations. Previously mounted network drives are not visible and the connect to server box turns red as soon as a colon is entered as is reuired for both smb and sftp

![image](https://user-images.githubusercontent.com/39475331/81175263-89a5b100-8fa3-11ea-9505-2b88f064a61e.png)
![image](https://user-images.githubusercontent.com/39475331/81175301-9f1adb00-8fa3-11ea-862b-05f624af1f17.png)

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/4586568/rednotebook.log)

**Comment by CSChisholm** [comment]
This is possibly a restriction of flatpaks rather than a bug in RedNotebook

**Comment by ObiSandwich** [comment]
> This is possibly a restriction of flatpaks rather than a bug in RedNotebook

I'm having the same problem on LMDE4 - Did you solve the problem? Please let me know how you did it?

Thanks,

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
