### ISSUE TITLE
Feature Request: Persistent ToDo List in the left column under the calendar widget.

### ISSUE THREAD

**Issue by ankurash** [jendrikseipp/rednotebook#493]
### Versions

RedNotebook version (make sure you have the latest version): v2.19

Operating system and version: Windows 10

### Expected behavior
A persistent todo list that is not dependent on the day/date so that pending tasks can be tracked beyond the end of a day.

### Actual behavior
NA
### Steps to reproduce the behavior
NA
### Log output when reproducing the behavior
NA
Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by jendrikseipp** [comment]
I'd consider this a duplicate of #498.
