### ISSUE TITLE
Bug: Reinstall/Upgrade installation resets the theme.

### ISSUE THREAD

**Issue by ankurash** [jendrikseipp/rednotebook#494]
### Versions

RedNotebook version (make sure you have the latest version): v2.19

Operating system and version: Windows 10

### Expected behavior
If there are no theme related code changes, **etc/gtk-3.0/settings.ini** should retain the theme settings on reinstall or upgrade install.

### Actual behavior
The contents of **etc/gtk-3.0/settings.ini** are reset, thereby resetting the theme to default.

### Steps to reproduce the behavior

1. Modify etc/gtk-3.0/settings.ini to change the theme
2. Run an installer to reinstall/upgrade the rednotebook installation.
3. Compare and verify the contents of etc/gtk-3.0/settings.ini

### Log output when reproducing behavior
NA
Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
NA

**Comment by jendrikseipp** [comment]
Thanks for the report! Maybe the best solution for this is to use a different mechanism for setting the theme. Can you try whether setting the GTK_THEME environment variable has an effect for RedNotebook? (https://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis)

**Comment by ankurash** [comment]
I tested setting the variable on Ubuntu 18.0 and Windows 10:
**On Ubuntu:**

1. Set `GTK_THEME=Adwaita` in the application shortcut ([ref ](https://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis))
**Result**: Works - overrides theme set from _settings.ini_. This won't affect any other app so that's good.
2. Set `GTK_THEME=Adwaita` in _.bashrc_
**Result**: Doesn't work - no effect.

**On Windows:**

1. Set `GTK_THEME=Adwaita` in user environment variables
**Result**: Works - overrides theme set from _settings.ini_. This might affect every GTK app on Windows.
2. Set `GTK_THEME=Adwaita` in the application shortcut ([ref](https://stackoverflow.com/a/34769146/1176315)) as follows:
`C:\Windows\System32\cmd.exe /c "SET GTK_THEME=Adwaita&& START /D ^"C:\Program Files (x86)\RedNotebook^" rednotebook.exe"`
and set application to "Run: Minimized" (application shortcut properties).
**Result**: Works - overrides theme set from _settings.ini_. This won't affect any other app but it did change the shortcut icon to a cmd icon, as expected.

**Comment by jendrikseipp** [comment]
Thanks for looking into this. Would you care to make a pull request that updates the instructions for how to change the theme on Windows by your second solution for Windows? Possibly, the instructions should recommend to create a new shortcut, since the old one might also be removed when upgrading the app.

**Comment by ankurash** [comment]
@jendrikseipp Can you describe your workspace/IDE setup for development of this project? 
Specifically, does one need to compile and run the project to see preview the documentation changes? 
I know it's markdown but we're writing and formatting it in python.

**Comment by jendrikseipp** [comment]
Yes, you'll have to run the app and hit CTRL+H to see the help document rendered as HTML. The markup format is txt2tags: https://txt2tags.org/markup.html

**Comment by ankurash** [comment]
@jendrikseipp Thank you. 
About the issue solution, I haven't found any way to set additional themes on windows. The methods I listen in the solution only work for default theme that come with GTK i.e. Adwaita and Adwaita Dark. So I think we should leave the current changes as well as add the new methods. Let me know if you think otherwise.

**Comment by jendrikseipp** [comment]
I think it makes sense to list all working options Windows users have for changing the theme and their pros and cons. I don't think we need to document this for Linux users.

So I guess the options are etc/gtk-3.0/settings.ini, GTK_THEME environment variable, shortcut.

**Comment by jendrikseipp** [comment]
I added this information to the help text. Thanks for your tests again!
