### ISSUE TITLE
Support for Markup Language (AsciiDoc)

### ISSUE THREAD

**Issue by nvdl** [jendrikseipp/rednotebook#497]
RedNotebook version: 2.19
OS: Ubuntu Bionic

It will be nice to have support for markup language (AsciiDoc for example).
It is a bit cumbersome to create tables using HTML tags.
Code highlighting is also well supported by AsciiDoc.

**Comment by jendrikseipp** [comment]
I am considering supporting a subset of Markdown, but that is a very long-term plan. For tables, you can actually use txt2tags table markup: https://txt2tags.org/markup.html Please note though that txt2tags tables might not be supported in future RedNotebook versions.
