### ISSUE TITLE
Support day-independent entries

### ISSUE THREAD

**Issue by nvdl** [jendrikseipp/rednotebook#498]
Sometimes, checklists, tips etc. are needed in day to day work. It will be nice to create such documents and make them available in a directory structure. They should be independent of the calendar.

For a while, one hack is to keep common stuff on the 1st of the current month but that requires migration every month.

**Comment by jendrikseipp** [comment]
I like the idea, however, I'd propose a solution that uses the functionality that already exists in RedNotebook. We can already add #hashtags and click on the to see which days contain them. So you could have a hashtag #tips to mark all days that contain tips and easily display them by clicking on the hashtag cloud. The only thing that needs improvement is how these results are displayed. Currently, the beginning of the day's text is shown, but it would be better to show the text next to the hashtag. So if a day looks like

```
This is some text.
#tips Do not cross the street on red.
This is more text.
```

the search for #tips should display "Do not cross the street on red.", i.e., everything that is on the same line as the hashtag, except the hashtag itself. Then you can get a nice list of tips, with the additional information of when you added them.

Pull requests welcome :-)

**Comment by nvdl** [comment]
This is a good suggestion. But, without testing, I can guess that it will take away the flexibility of having a document with ordered information. I don't know if tags can be applied to blocks of texts either.

If having a standalone document  is possible, it will allow easy management of code snippets as well. Just create files with code blocks marked with # tags.

**Comment by jendrikseipp** [comment]
I agree that date-independent notes are very useful. However, for these I wouldn't use a journal tool.
