### ISSUE TITLE
Alt+Up/Down arrow keys expand selection to new lines when shifting lines

### ISSUE THREAD

**Issue by nvdl** [jendrikseipp/rednotebook#499]
### Versions
RedNotebook version: 2.19
Operating system and version: Ubuntu Bionic

### Expected behavior:
Only selected lines move.

### Actual behavior
Extra lines get selected during up/down shifting of lines.

**Comment by jendrikseipp** [comment]
Interesting, I didn't even know the shortcut, thanks! On Ubuntu this seems to work fine. It's probably a bug in the Windows version of GTK. Hopefully, we can update that library soon, at which point the error might go away.

**Comment by nvdl** [comment]
I am getting the issue on Ubuntu Bionic 18.04. Installed it via flatpak.

Try moving a line that is long and has wrapped around. After a few moves, the extra lines get selected. Try the same in Gedit and it works fine.
