### ISSUE TITLE
I am getting an error when trying to open the rednotebook

### ISSUE THREAD

**Issue by vindaso** [jendrikseipp/rednotebook#501]
### Versions

Version is 2.19

Operating system and version:

Windows 10

### Expected behavior

After double click on the icon the rednotebook will be displayed.

### Actual behavior

After double click on the icon I got the error attached.
![Rednotebook issue](https://user-images.githubusercontent.com/65557195/82240057-02d3cb00-98f7-11ea-962a-f4eb65189fce.png)

### Steps to reproduce the behavior

Just double click on the rednotebook icon

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/4645509/rednotebook.log)

**Comment by vindaso** [comment]
It was working perfectly last Friday.  Today because of this, I did uninstalled and tried to install again but didn't work.

**Comment by jendrikseipp** [comment]
Here is my attempt at upgrading the underlying stack of libraries for Windows: #478 Unfortunately, the app crashes and I don't know how to debug it.

**Comment by jendrikseipp** [comment]
#478 has been merged and released in version 2.27. Does the error persist in that version?
