### ISSUE TITLE
Feature request: Fixed image sizeImage size

### ISSUE THREAD

**Issue by Murmele** [jendrikseipp/rednotebook#503]
### Versions
RedNotebook version (make sure you have the latest version): 2.19

Operating system and version: linux

### Expected behavior
Would be nice if there is an option to set the size of the image or the width of the hole document.
Something like in latex: 
\includegraphics[width=0.33\textwidth, angle=30]{test.png}

### Actual behavior
All images have different sizes

### Steps to reproduce the behavior
1) Create new document and add images of different size
2) Export Diary to HTML
3) Check size of the images

**Comment by jendrikseipp** [comment]
Nice idea, but out of scope for RedNotebook.
