### ISSUE TITLE
Feature request: disable smooth scrolling 

### ISSUE THREAD

**Issue by danielrosehilljlm** [jendrikseipp/rednotebook#507]
## Versions

2.19 

##

Linux

## Feature request

When you add a line to the bottom of the text editor there is some kind of very noticeable smooth scroll effect that loads.

Some weird people, including me, hate smooth scrolling and find it distracting.

Such weird people would prefer a more jagged experience in which new lines were made visible in an instantaneous but abrupt manner.

**Comment by jendrikseipp** [comment]
I think this behaviour comes from your OS, not from RedNotebook.

**Comment by danielrosehilljlm** [comment]
> I think this behaviour comes from your OS, not from RedNotebook.

Fair enough. LXDE is pretty barebones and doesn't have much in the way of effects. But in any event, it's not something that would bother most people so better ignored!

**Comment by danielrosehilljlm** [comment]
> I think this behaviour comes from your OS, not from RedNotebook.

Great tool by the way. Thank you for putting it together!

**Comment by jendrikseipp** [comment]
Thanks, appreciate it!
