### ISSUE TITLE
Feature request: Dock widget area

### ISSUE THREAD

**Issue by danielrosehilljlm** [jendrikseipp/rednotebook#508]
### Versions

2.19

Operating system and version:

Ubuntu 20.04 with LXDE

## Feature request

I'm surprised that there is no feature to close / dock the calendar and tag cloud widgets.

My workaround is to drag the divider back and forth as I prefer a distraction-free writing environment. However a docking and undocking button would be a more convenient solution than having to drag the movable column back and forth when alternating writing entries and navigating between dates.

**Comment by jendrikseipp** [comment]
Yes, this sounds like a nice addition. If anybody wants to work on this, feel free to open a pull request.

**Comment by jendrikseipp** [comment]
Actually, it should already be possible to move the left panel slider all the way to the left to completely hide the calendar and tag cloud widgets.
