### ISSUE TITLE
RedNotebook hangs, version 2.19

### ISSUE THREAD

**Issue by p-bags** [jendrikseipp/rednotebook#511]
### Versions

RedNotebook version (make sure you have the latest version): 2.19 (I'm a new user)

Operating system and version: Ubuntu Linux 20.04 LTS, Gnome version 3.36.3

### Actual behavior
Hanging. This is intermittent and I don't know whether another program is interfering. This last time it happened, Slack was open, as was Firefox (latest version), and three jpg images. I can click on various dates in the calendar and see the contents, but I cannot enter any new text or conduct searches. Unresponsive to keyboard entries.

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by jendrikseipp** [comment]
Any output in the logfile under $HOME/.rednotebook/rednotebook.log ?

**Comment by p-bags** [comment]
Yes! attached!
(I am NOT a techie, so wouldn't know how to interpret what's in the log)
The last time it hung was yesterday morning. I had to reboot the computer to have it function properly.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by RJ722** [comment]
@p-bags I don't see an attachment with your comment on GitHub. My hunch is that when you reply to the GitHub email, GitHub strips away all attachments because of security reasons. You'd need to visit https://github.com/jendrikseipp/rednotebook/issues/511 and manually attach a file in the comment box.

**Comment by p-bags** [comment]
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/4928378/rednotebook.log)

**Comment by p-bags** [comment]
Done! Thanks!
I just crashed again. But more than just RedNotebook crashing, I couldn't do other things either, no keyboard responses accepted anywhere, or mouse clicks except closing windows. So I guess this might be a Linux issue...nothing I've done has crashed, though, except while using RedNotebook.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jendrikseipp** [comment]
Thanks! The log contains nothing suspicious. And I agree, this sounds like a Linux problem.

**Comment by p-bags** [comment]
I really like this program. I'm actually copying and pasting 6,200 entries from an online program called Penzu. The only way to do it was to export to a pdf...
I appreciate the help and quick response!
