### ISSUE TITLE
Insert / Format: duplicated menu items?

### ISSUE THREAD

**Issue by p2635** [jendrikseipp/rednotebook#525]
**Is your feature request related to a problem? Please describe.**
I think that the menu items 'Insert' and 'Format' appear twice, they appear in the editor and in the main menu but I think this is just duplicating menus for no reason. I see no difference between them.

**Describe the solution you'd like**
Possibly choose one place and remove the other.

* If removing from the main menu, then obviously the keyboard shortcuts will need to be shown elsewhere
* Remove it from the editor, keep it in the main menu

**Describe alternatives you've considered**
Have an option to hide them in the editor.

**Versions:**
- RedNotebook version 2.20
- Operating system and version: Win10

**Comment by jendrikseipp** [comment]
I think it's fine to keep both locations.
