### ISSUE TITLE
Option to Hide/Display Calendar and Search Pane

### ISSUE THREAD

**Issue by p2635** [jendrikseipp/rednotebook#527]
**Is your feature request related to a problem? Please describe.**
Unless I am searching or navigating dairy entries by date, I don't want to see the navigation for the calendar or search pane. Hiding both would give me space to focus on the editor and writing the current entry.

**Describe the solution you'd like**
Maybe a button here which says 'Display/Hide Calendar and Search'.
![image](https://user-images.githubusercontent.com/4522927/90794561-d455f980-e304-11ea-9293-17ce88a2c951.png)

Whatever the setting was set by the user, the setting persist after closing and relaunching RedNotebook.

**Describe alternatives you've considered**
Can't think of any at the moment

**Versions:**
- RedNotebook version 2.20
- Operating system and version: Windows 10

**Comment by AMB2800** [comment]
This may not be what you're after, but on my install I can simply drag the calendar/search window to the left and it is no longer visible.  When I want to see it again, grab the left-edge and drag it back so it is visible.

**Comment by p2635** [comment]
I'm no longer user rednotebook so closing this.
