### ISSUE TITLE
Feature request: Start RedNotebook minimised in tray

### ISSUE THREAD

**Issue by p2635** [jendrikseipp/rednotebook#528]
**Is your feature request related to a problem? Please describe.**
I have RedNotebook in my startup so when I turn on my PC, it opens fine and starts a new window. But I want it to start in the tray instead.

**Describe the solution you'd like**
Perhaps an option in the settings area for start minimised or if you can provide me with an extra line in the shortcut like 'rednotebook --start-minimised' then that would be enough for me.

**Versions:**
- RedNotebook version: 2.2
- Operating system and version: Win10 64bit

**Comment by jendrikseipp** [comment]
To keep the project maintainable, this feature is considered out of scope for RedNotebook.
