### ISSUE TITLE
Please add option to scale images in preview

### ISSUE THREAD

**Issue by carygravel** [jendrikseipp/rednotebook#535]
**Is your feature request related to a problem? Please describe.**
Typically, my images are straight from a digital camera, and therefore appear huge in the preview.

**Describe the solution you'd like**
It would be nice if there was an option to scale them to fit the preview window.

**Describe alternatives you've considered**
I could scale them manually, but just for the preview, this is OTT.

**Versions:**
2.10, cloned from github
- Operating system and version:
Debian Testing - System info: machine: x86_64, platform: Linux-5.8.0-2-amd64-x86_64-with-glibc2.29, processor: , python_version: 3.8.6, release: 5.8.0-2-amd64, system: Linux, GTK: (3, 24, 23), Glib: (2, 66, 0), PyGObject: (3, 38, 0), YAML: 5.3.1

**Comment by jendrikseipp** [comment]
You can append ?200 to the image filename to scale your image to a width of 200 pixels. The picture chooser also offers a graphical solution for this (see checkbox in the bottom left of the dialog).

**Comment by carygravel** [comment]
Thanks for the hint. Can you implement ?fit to make it fit the preview screen? And add something so that right-clicking on the filename adds options to add the ?scale or ?fit, please.

**Comment by carygravel** [comment]
And please document the ?size feature in the help.
