### ISSUE TITLE
Please add a method of mass-importing entries somehow

### ISSUE THREAD

**Issue by carygravel** [jendrikseipp/rednotebook#536]
**Is your feature request related to a problem? Please describe.**
I've got 40+ years worth of diary entries in plain text or .odt, and I don't want to manually copy-paste them into rednotebook a day at a time.

**Describe the solution you'd like**
Some sort of template-based solution where rednotebook parses out the date from the text.

**Versions:**
RedNotebook version: 2.20
Debian Testing - machine: x86_64, platform: Linux-5.8.0-2-amd64-x86_64-with-glibc2.29, processor: , python_version: 3.8.6, release: 5.8.0-2-amd64, system: Linux, GTK: (3, 24, 23), Glib: (2, 66, 0), PyGObject: (3, 38, 0), YAML: 5.3.1

**Comment by jendrikseipp** [comment]
The RedNotebook format is just a collection of YAML files. You can use any external tool for preparing these YAML files, but in most cases you'll have to write your own tool since everybody's old file conventions are a bit different. The help document (Ctrl+H) has more info on the YAML format.

**Comment by carygravel** [comment]
This is true, but just playing with the data like this runs the risk of unexpected consequences.

How about exposing enough of the Python API to do stuff like

rednotebook.add_entry(date_object, a_load_of_text)

And then the use just has to write the reading half and not worry about the rest.

**Comment by jendrikseipp** [comment]
The API is already present. You'll want to import rednotebook/storage.py and use the `save_months_to_disk()` function.
