### ISSUE TITLE
Image filenames should not be included in tag cloud

### ISSUE THREAD

**Issue by carygravel** [jendrikseipp/rednotebook#537]
**Describe the bug**
Image filenames are currently included in the tag cloud

**To Reproduce**

1. Add an image
2. If you don't have too many other entries, the filename is now in the tag cloud

**Expected behavior**
Only real words should be in the tag cloud

**Versions:**
- RedNotebook version: 2.20
- System info: machine: x86_64, platform: Linux-5.8.0-2-amd64-x86_64-with-glibc2.29, processor: , python_version: 3.8.6, release: 5.8.0-2-amd64, system: Linux, GTK: (3, 24, 23), Glib: (2, 66, 0), PyGObject: (3, 38, 0), YAML: 5.3.1

**Comment by jendrikseipp** [comment]
I agree, this sounds like a good change.

**Comment by laraconda** [comment]
Urls are also included in the cloud.

**Comment by laraconda** [comment]
I also just discovered that tags get treated as words and appear in the cloud too, just without the '#'. 
As in '#blessed' -> 'blessed'.

This is not as bad as the other two cases imo. I think it could be solved by removing any string in the tags list from the words list. But this method could have the side effect of removing a very common word from the words cloud if it is also used as a tag.

**Comment by laraconda** [comment]
Yeah, I'll do it in this same pull request.
