### ISSUE TITLE
References don't work on Windows

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#540]
[Reported by Chris]

**Describe the bug**

The feature that links between days doesn't seem to work in version 2.20 on Windows. (Windows 10 Pro for Workstations Version 2004 OS Build 19041.450)

On my 9/16/2020 entry, I added this text:
```
//{**Update 10/14/2020:** See [2020-10-14] for new location of files.}//
```

It shows up [...] in preview mode

But when I click the link, nothing happens.

NOTE: As a test, I removed the slashes and curly brackets. The behavior doesn't change.
...and yes, there is an entry on 10/14/2020.

**Comment by jendrikseipp** [comment]
@idle-code Could you try to reproduce the error on Windows?

**Comment by idle-code** [comment]
OK, but I will need to install windows 10 on some vm first.

**Comment by jendrikseipp** [comment]
Sure, no hurry. Thanks!

**Comment by idle-code** [comment]
I was able to duplicate the issue on my VM quite easliy. But building rednotebook on it has taken a bit longer than anticipated ;)
It seems that I have implemented the original feature for WebKit2-based HtmlView only. I wonder if it works (and if so - how) on my other win8 machine...
