### ISSUE TITLE
Does not work well with display scaling

### ISSUE THREAD

**Issue by SSSachith** [jendrikseipp/rednotebook#541]
Does not scale with 150% scaling in my UHD screen in windows 10. Text and layout appears blurry.

**Versions:**
- RedNotebook version 2.2
- Operating system and version: Windowss 10

**Comment by ric2016** [comment]
A workaround that works for me is to disable the custom scaling for this specific application. This doesn't even affect the text and layout sizes: Everything is the same size as with scaling, only not blurry. (So the scaling doesn't seem to have the intended effect on this application anyway)

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
