### ISSUE TITLE
Multiple instance of rednote opened in windows 10

### ISSUE THREAD

**Issue by jiafanzhou** [jendrikseipp/rednotebook#543]
![image](https://user-images.githubusercontent.com/220490/98242283-1e459780-1f64-11eb-9bfb-d3b885bec9e8.png)

**Comment by l3td33r** [comment]
Same for linux. Suggested solution: Prevent opening a new instance, if there is already one running.

Multiple instances could lead to disaster, if we edit something in a different instance by mistake and then it is saved.

**Comment by jendrikseipp** [comment]
I fully agree. This should be fixable by using the GtkApplication class. I took a stab at this in a feature branch and will try to backport it into the main branch.

**Comment by jendrikseipp** [comment]
This has been implemented in version 2.27.

**Comment by mmeyer56** [comment]
Please open again because on version 2.31 doesnt work !! Before the update multiple instance worked perfectly (Windows 10 Pro)

**Comment by jendrikseipp** [comment]
This is by design. Having multiple instances open would be a recipe for data loss currently. It would be a different story if different instances only allowed to have different journals open, but this cannot be enforced at this moment.
