### ISSUE TITLE
More than one language in a page. 

### ISSUE THREAD

**Issue by tuxedotje** [jendrikseipp/rednotebook#545]
**Is your feature request related to a problem? Please describe.**
<!-I use different languages, but cannot use these in rednotebook. because it cannot do more than 1 language in a page  [...]-->

**Describe the solution you'd like**
<!I like to select a part of text and define the languaage for that part of text. -->

**Describe alternatives you've considered**

**Versions:**
- RedNotebook version :  2.20
- Operating system and version:
Fedora 33

**Comment by jendrikseipp** [comment]
To keep the project maintainable, this feature is considered out of scope.
