### ISSUE TITLE
More than one language in a page. 

### ISSUE THREAD

**Issue by tuxedotje** [jendrikseipp/rednotebook#546]
**Is your feature request related to a problem? Please describe.*
I would like to be able to write more than one language in a page. 

**Describe the solution you'd like**-select a text and define language for that part, 

**Describe alternatives you've considered**

**Versions:**
- RedNotebook version--2.20
- Operating system and version:  Fedora 33

**Comment by jendrikseipp** [comment]
Sorry, but this falls outside of the app's scope.
