### ISSUE TITLE
Tries to load then aborts

### ISSUE THREAD

**Issue by cBodenwinkler** [jendrikseipp/rednotebook#549]
Trying to open it after download via POP_Shop. It loads for a few seconds and then aborts.

**Comment by jendrikseipp** [comment]
Can you try to open it from the terminal and post the log here, please?

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
