### ISSUE TITLE
Keyword panel should exclude date/time stamps

### ISSUE THREAD

**Issue by david-burleigh** [jendrikseipp/rednotebook#557]
When I am taking notes in a recorded discussion involving many people, I use the Ctrl-D action to insert a date/time at the beginning of what each speaker says, followed by the name of the speaker and what he or she says. This helps the person who transcribes the discussion from the recording identify each speaker, whose voice he or she may not recognize. However, the text of the dates and times becomes prominent in the keyword panel, cluttering it up, and making it  almost useless. I wish these timestamps would automatically be ignored when determining the "weight" of each word.

**Comment by jendrikseipp** [comment]
Thanks for the report! Which words do you want to ignore exactly? Can you add them to the ignore list in the preferences dialog? Note that the ignore list accepts regular expressions.

**Comment by jendrikseipp** [comment]
Closing this for some spring cleaning. Feel free to reopen if the issue persists.
