### ISSUE TITLE
Version 2.21 on Windows 10 copy/cut/paste not working

### ISSUE THREAD

**Issue by stevenbrown2** [jendrikseipp/rednotebook#559]
**Describe the bug**
just upgraded to version 2.21 on Windows 10
tried cut/paste did not work
tried copy/paste did not work
tried using keyboard shortcuts as well as menu same result.
reverted back to version 2.20 works as expected

**To Reproduce**

1. installed version 2.21
2. selected some text
3. Ctrl+x - text disappeared
4. Ctrl+v - no response
5. menus Edit - Paste - no response

**Expected behavior**

I use cut/copy/paste regularly so I have reverted back to version 2.20 as log file shows

**Versions:**
- RedNotebook version 2.21
- Operating system and version: Windows 10 Pro version 20H2

**Log output when reproducing bug**
Log file only references version 2.20

**Comment by ycwang427** [comment]
Copy/cut/paste of version 2.21 seems to work for me on Windows 10 Home 1909.

**Comment by stevenbrown2** [comment]
tried upgrading again - all seems to be working now.
very strange indeed.....
