### ISSUE TITLE
Find days with no entry

### ISSUE THREAD

**Issue by carygravel** [jendrikseipp/rednotebook#566]
**Is your feature request related to a problem? Please describe.**
The statistics window show the proportion of days with entries. I'd like to locate those days without entries, without having to click through years of them.

**Describe the solution you'd like**
Maybe arrows next to the forward and back buttons. Or a different mode for the forward and back buttons, so that they skip to the next empty day, rather than non-empty day.

**Describe alternatives you've considered**

**Versions:**
- RedNotebook version 2.21
- Operating system and version: debian testing

**Comment by jendrikseipp** [comment]
To keep the project maintainable, this feature is considered out of scope for RedNotebook.
