### ISSUE TITLE
Crashes on CentOs 8 

### ISSUE THREAD

**Issue by lbm-services** [jendrikseipp/rednotebook#568]
**Describe the bug**
free(): invalid pointer

**To Reproduce**

1. pip3 install --user .
2. rednotebook

**Versions:**
- RedNotebook version :
- Operating system and version:
- CentOS Stream release 8

**Log output when reproducing bug**
2021-03-24 11:42:42,210 INFO     Writing log to file "/home/hli/.rednotebook/rednotebook.log"
2021-03-24 11:42:42,210 INFO     System encoding: utf-8
2021-03-24 11:42:42,210 INFO     Language code: de_DE

**Comment by jendrikseipp** [comment]
Is there anything helpful in the terminal output?

**Comment by MaxKrummenacher** [comment]
I see the same behaviour on opensuse 15.2.
The pull request #583 fixes this for me and rednotebook starts as expected.

**Comment by jendrikseipp** [comment]
@lbm-services Can you please run the latest revision from the repo and check if MaxKrummenacher's patch fixes your issue?

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
