### ISSUE TITLE
renotebook does not open / crashes in Fedora 34 beta 1.3

### ISSUE THREAD

**Issue by tuxedotje** [jendrikseipp/rednotebook#572]
**Describe the bug**
renotebook does not open / crashes in Fedora 34 beta 1.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**
- RedNotebook version just installed 
Fedora 34 beta 1.3
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/6249025/rednotebook.log)

**Log output when reproducing bug**

**Comment by jendrikseipp** [comment]
Hmm, I don't understand what's going wrong there. Maybe it helps to report the bug to the maintainers of the RedNotebook fedora package (https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=rednotebook&product=Fedora&product=Fedora%20EPEL)?

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
