### ISSUE TITLE
Make flatpak package use a newer version of org.gnome.Platform (the used one is eol) & update the package itself to 2.21 (& its not starting, but thats maybe a result from the others)

### ISSUE THREAD

**Issue by qwertele** [jendrikseipp/rednotebook#573]
**Describe the bug**
- The flatpak package uses org.gnome.Platform 3.36. That version of gnome is end of life since 13.02.2021.
- The rednotebook flatpack is only version 2.20.

Maybe important additional notice: the rednotebook app is not running on my computer either. Im not really trying to fix this or providing details into an issue, because im hoping that the problem will be fixed by updating the flatpak package, and personally, i will switch to the .deb-version now. On the very bottom of this issue is a terminal output when i try to run it.

**To Reproduce**
install rednotebook flatpak, run flatpak update, get warning message about org.gnome.Platform end of life.

**Expected behavior**
- flatpak package using a newer version of org.gnome.Platform, for example 3.40.
- flatpak package being version 2.21

**Screenshots**
No screenshots, but the two copied messages from the terminal:
when running flatpak update: "Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform."

When chcking which app needs the 3.36 version of gnome: "Error: Can't remove org.gnome.Platform/x86_64/3.36, it is needed for: app.rednotebook.RedNotebook/x86_64/stable
error: Failed to uninstall org.gnome.Platform: Can't remove org.gnome.Platform/x86_64/3.36, it is needed for: app.rednotebook.RedNotebook/x86_64/stable"

**Versions:**
- RedNotebook version : 2.20 (newest one available through flatpak)
- Operating system and version: Pop OS, Linux 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Log output when reproducing bug**
Did not find a logfile. Since the main points of this issue dont need one (i think), i can post the output of me trying to start the app (and it failing), in case that might be interesting:
$ flatpak run app.rednotebook.RedNotebook
Adding /app/lib/python3.7/site-packages to sys.path
Traceback (most recent call last):
  File "/app/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/rednotebook", line 12, in <module>
    import rednotebook.journal
  File "/app/lib/python3.7/site-packages/rednotebook/journal.py", line 90, in <module>
    elibintl.install(GETTEXT_DOMAIN, LOCALE_PATH, libintl=None)
  File "/app/lib/python3.7/site-packages/rednotebook/external/elibintl.py", line 472, in install
    _install(domain, localedir, True, libintl=libintl)
  File "/app/lib/python3.7/site-packages/rednotebook/external/elibintl.py", line 416, in _install
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by jendrikseipp** [comment]
This should be fixed now. Thanks @dgcampea !
