### ISSUE TITLE
GPG Signature error

### ISSUE THREAD

**Issue by thomasfaller** [jendrikseipp/rednotebook#576]
When trying to install via Flatpak on Fedora 34, I get the following error:

```bash
Error: Error pulling from repo: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)
error: Failed to install org.gnome.Platform: Error pulling from repo: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)

```

**System info**
OS: Feodra 34 x86_64
Kernel: 5.11.17-300.fc34.x86_64

**Comment by jendrikseipp** [comment]
Can you try removing the flathub repo and adding it back again?

**Comment by jendrikseipp** [comment]
I'm closing this issue for now. Feel free to reopen if the problem persists.
