### ISSUE TITLE
Go to next date shortcut.

### ISSUE THREAD

**Issue by tuxedotje** [jendrikseipp/rednotebook#580]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The existing shortcut to go to next date does not go to empty date. I would like a shortcut to go to every next date , empty or not. 

**Describe alternatives you've considered**

**Versions:**
- RedNotebook version :
- Operating system and version:
Fedora 34

**Comment by jendrikseipp** [comment]
I wouldn't want to add a new button or option for this. I think it's best to use the calendar for this.
