### ISSUE TITLE
permissions on edited files

### ISSUE THREAD

**Issue by amisios** [jendrikseipp/rednotebook#591]
Hello.

Thanks very much for creating and maintaining rednotebook.

I have this issue, and I did not find anything similar here (Its really between a bug and a feature request). I understand it is a feature but it is inconvenient for me.
On linux, when I start a new entry/day or just edit an existing one, the permissions of the corresponding file (referring to the month e.g. 2021-08.txt) are set to 600 (read/write for owner, nothing for group and world). This is really not working for me. I have to change permissions to 660 every time. I need the file to have group permissions for read and write.
Is there a way (through settings?) that I can change the default permissions of rednotebook and set them to the ones I want?

I understand that this might be the default from privacy concerns. (I am not sure)
On the other hand, I believe setting the permissions of the umask to the edited/created file by default is more reasonable.
My umask, for example, is 002, which corresponds to 664 I think.

Best,
A.M.

**Comment by jendrikseipp** [comment]
Thanks for the report! There is currently no setting for changing the file permissions. The current solution indeed stems from privacy concerns and there are currently no plans to make this configurable. I hope it's fine for your workflow to change the permissions manually.
