### ISSUE TITLE
Can't escape some special characters

### ISSUE THREAD

**Issue by SpHex4C** [jendrikseipp/rednotebook#592]
Hello, i'd like to sometimes write date and time in the `[21/02/2021 | 02:23]` format, but it never shows up as just `[21/02/2021 | 02:23]`, even if i add backslashes to various places.
Is there a way to make it show up without any weird formating?

**Comment by jendrikseipp** [comment]
This format is used to add links to dates. You'll have to use a slightly different format to avoid it being converted to a link.

**Comment by SpHex4C** [comment]
Oh, so there's no way to escape this synthax?
That's too bad :/
