### ISSUE TITLE
No way to overwrite existing backup

### ISSUE THREAD

**Issue by daVe55w** [jendrikseipp/rednotebook#596]
If you attempt to save a backup with the same date as an existing backup, a warning window states "A file with the name xxxxx already exists. Do you want to replace it"?

However, the only option is Cancel. OK is missing. Screenshot below.
The only way seems to be to first delete the existing backup and then save the new one.

<img width="625" alt="rednotebook backup" src="https://user-images.githubusercontent.com/31006631/134698719-e1ef2317-0598-46c7-a45f-c31d5b08c580.png">

**Comment by jendrikseipp** [comment]
I consider this a feature rather than a bug. Since the backups are so small, I would always choose a new filename.
