### ISSUE TITLE
Crash when strikethrough certain string

### ISSUE THREAD

**Issue by ScumCoder** [jendrikseipp/rednotebook#597]
Reproducibility: 100%

Way to reproduce:
1) copy the attached file to the data folder:
[2021-09.txt](https://github.com/jendrikseipp/rednotebook/files/7247574/2021-09.txt)
2) launch program, navigate to the corresponding day
3) select the text string following the tag (`послать в`):
![1](https://user-images.githubusercontent.com/6260365/135172745-c0cc1ae3-78c6-4fd5-9b35-e8453a895cac.png)
4) hit Ctrl+K

Expected result:
![2](https://user-images.githubusercontent.com/6260365/135172754-65902d44-8b8a-4fc1-b972-77ed786bedb1.png)

Actual result:
App crashes with a trap in libpango:
```
[ 3085.115212] traps: rednotebook[19521] trap divide error ip:7f1255329fef sp:7ffc75619300 error:0 in libpango-1.0.so.0.4800.9[7f1255307000+29000]
```
Understandingly, nothing is written to the log.

Version:
2.22 from Flatpak
OS: OpenSuSE 15.3

[configuration.cfg.zip](https://github.com/jendrikseipp/rednotebook/files/7247582/configuration.cfg.zip)
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/7247583/rednotebook.log)

**Comment by jendrikseipp** [comment]
Thanks for the detailed report! This seems to be an error in Pango. Would you care to report the issue there?

**Comment by ScumCoder** [comment]
I might try, but the only way I can do this is by sending them this exact bugreport, and I'm not sure they will be glad.
Do I understand it right that you've checked the library calls in your code and they seem correct? If yes, maybe it will be better to send the library developers just the arguments that cause the crash?

**Comment by jendrikseipp** [comment]
I haven't reproduced the error myself, no. Before reporting this to the pango project, you'd have to reduce it to a minimal example. Not sure how to do that for pango, but their docs will probably tell you how.
