### ISSUE TITLE
Option to have text after image (Instead of side by side)

### ISSUE THREAD

**Issue by Adithya-Jayan** [jendrikseipp/rednotebook#605]
*The problem*
It's quite frustrating when you add in a small image. Any text typed in after the image appears on the side instead of appearing below it. The only way to get the new text below the image is to use multiple line-breaks typed in manually.

*How I want the image to look*
![image](https://user-images.githubusercontent.com/50314485/147833662-51ea93f9-5f68-407e-8962-a45129f03256.png)

*Code required to do so*
![image](https://user-images.githubusercontent.com/50314485/147833687-64cf9b7d-ec50-4ada-89e5-80ce003ba603.png)

**Describe the solution you'd like**
I can think of two possible solutions:
- A special line break character (That can automatically act as multiple line breaks so the cursor continues below the image)
-  An option to select whether side-by-side image and text should be allowed or not. (This could be per-image or overall)

**Describe alternatives you've considered**
The only alternative to this would be to either leave the image full-sized (So there is no space for text to appear on it's side , or to manually move the cursor below the image using blank lines)

**Versions:**
- RedNotebook version 2.22:
- Operating system and version: Windows 10

**Comment by jendrikseipp** [comment]
I think a simple solution is to leave an empty line above and below the image.
