### ISSUE TITLE
crashes when LC_ALL not set and started from app launcher

### ISSUE THREAD

**Issue by mepreston** [jendrikseipp/rednotebook#613]
https://bugzilla.redhat.com/show_bug.cgi?id=2041257

Description of problem:
lf a locale setting is set in .bashrc which requires LC_ALL to be unset
then rednotebook will not launch via autostart nor from the
desktop env app launcher, i.e. KDE

Version-Release number of selected component (if applicable):
FC35 and rednotebook 2.22

How reproducible:
always

Steps to Reproduce:
1. set LC_TIME in .bashrc to export LC_TIME="C.UTF-8". 
2. logout and back in. 
3. start rednotebook from the desktop launcher or desktop application link and it will crash.

It works fine as long as LC_ALL is set which i cannot since i am changing
LC_TIME. I can start the app just fine if i open a bash shell and run it from there, some reason it doesn't mind that LC_ALL isn't set when run from an interactive shell. 

This hasn't been working for me since FC34 upgrade but was hoping someone else would file a bug or it would just get fixed.

Actual results:
crash, see callback stack below

Expected results:
it shouldn't crash

Additional info:

Adding /usr/lib/python3.10/site-packages to sys.path
Traceback (most recent call last):
File "/usr/bin/rednotebook", line 6, in <module>
import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/rednotebook", line 12, in <module>
import rednotebook.journal
File "/usr/lib/python3.10/site-packages/rednotebook/journal.py", line 100, in <module>
elibintl.install(GETTEXT_DOMAIN, LOCALE_PATH, libintl=None)
File "/usr/lib/python3.10/site-packages/rednotebook/external/elibintl.py", line 472, in install
_install(domain, localedir, True, libintl=libintl)
File "/usr/lib/python3.10/site-packages/rednotebook/external/elibintl.py", line 416, in _install
locale.setlocale(locale.LC_ALL, '')
File "/usr/lib64/python3.10/locale.py", line 620, in setlocale
return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by jendrikseipp** [comment]
Thanks for the report! Should be fixed now. Can you confirm?

**Comment by mepreston** [comment]
it just got ported to fedora and yes it does seem to be working fine now.
thanks.
