### ISSUE TITLE
Red Note Book has stopped working

### ISSUE THREAD

**Issue by Hamtook** [jendrikseipp/rednotebook#615]
I have been using Red Notebook ( 2.24 ) on Linux Zorin ( 15.3 ) for a long time without any problem. It has worked wonderfully until now, when it simply stopped working.
I have just made a donation and have re-installed Red Notebook ( 2.24 ) without any improvement.
The symptoms are -
Red Notebook opens but does not contain any data.
The program will not open / import the back up (.zip ) back up file.
I notice that the back up file name is in very faint text, not in the usual bolder text.
Could you please help me with a solution to this problem.
Thank you.

David Grabham.
( dj.grabham@bigpond.com )

===========================================

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**
- RedNotebook version :
- Operating system and version:

**Log output when reproducing bug**

**Comment by jendrikseipp** [comment]
I suggest to have a look at the log output. It shows which month files are read. Zip files are not read, but must be unpacked first.

**Comment by kathenas** [comment]
Just before I do any testing. Which version of Zorin is this?

* Pro
* Core
* Lite

**Comment by jendrikseipp** [comment]
Feel free to reopen if the issue persists.
