### ISSUE TITLE
Missing icons, gnome and zero standards.

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#616]
**Describe the bug:**

Sorry, health and being busy has delayed me doing this report.

Icons in certain circumstances will be missing due to the fact that the GNOME project is not too fussed about "standard icon names" any longer.

Current beta 36 of Fedora image.

![Screenshot from 2022-04-12 10-02-29](https://user-images.githubusercontent.com/68813857/162925451-a41a86f3-4b1e-49da-9b5a-22b69a146e31.png)

@fabaff Please look at Fedora bug reports and PR. I would hate for RedNotebook in Fedora 36 to be old and remain broken for any extended period of time.

This is caused by adwaita no longer thinking standards are necessary. See:

https://gitlab.gnome.org/GNOME/gtk/-/issues/4765

and/or

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/180

Yes, other apps are also affected.

**Versions:**
- RedNotebook version: >= 2.22
- Operating system and version: Fedora >= 36
- 
Does not yet affect Debian or its derivatives. But will eventually.

**Notes:**

As you will see from the above bug reports, GNOME is not too fussed and the likelihood of this issue being simply fixed quickly and permanently is slim. The alternate solution here is having all icons for RedNotebook within the upstream package. This will:

* Stop this issue arising again.
* Make look and feel consistent for RedNotedbook across all distributions and Desktop Environments.

Thoughts?

**Comment by jendrikseipp** [comment]
Hmm, not sure about the best plan of action. Do you know how other apps are handling this problem?

**Comment by kathenas** [comment]
I thought I would allow you to think on it. Sadly, at the moment I am very busy with other things and I am going to have to leave this one to others.

**Comment by jendrikseipp** [comment]
No worries, thanks for bringing this to our attention!

**Comment by jendrikseipp** [comment]
I was able to fix the icons problem in the `upgrade-pyinstaller` branch. Will cherry-pick it into the main branch soon.

**Comment by kathenas** [comment]
Hi Jendrik,

Apologies for the delay in reply. I will look at the branch this weekend in and among packing as I
am moving home at the start of next month. Living the dream of boxes and tape. :-)

Regards

Phil


On Thu, 2022-05-05 at 00:44 -0700, Jendrik Seipp wrote:
> I was able to fix the icons problem in the upgrade-pyinstaller branch. Will cherry-pick it into
> the main branch soon.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
*** Playing the game for the games own sake. ***

Associations:

* Debian Maintainer (DM)
* Fedora/EPEL Maintainer.
* Contributor member of the AlmaLinux foundation.

WWW: https://kathenas.org

Twitter: @kathenasorg

Instagram: @kathenasorg

IRC: kathenas

GPG: 724AA9B52F024C8B

**Comment by jendrikseipp** [comment]
I cherry-picked the icon changes into the main branch now. No need to look into the feature branch. Good luck with the move!

**Comment by kathenas** [comment]
On Fri, 2022-05-13 at 04:47 -0700, Jendrik Seipp wrote:
> I cherry-picked the icon changes into the main branch now. No need to look into the feature
> branch. Good luck with the move!
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.


Hi Jendrik,

Had chance to test on Debian unstable and Fedora rawhide this morning and all looks good.

Let me know when you push a release and I will package and upload to Debian. I no longer need
validation and I now can upload rednotebook straight into Debian unstable.

Regards

Phil

-- 
*** Playing the game for the games own sake. ***

Associations:

* Debian Maintainer (DM)
* Fedora/EPEL Maintainer.
* Contributor member of the AlmaLinux foundation.

WWW: https://kathenas.org

Twitter: @kathenasorg

Instagram: @kathenasorg

IRC: kathenas

GPG: 724AA9B52F024C8B

**Comment by jendrikseipp** [comment]
Great, thanks for testing this! I just made a new release.

**Comment by kathenas** [comment]
2.25 has now been uploaded and accepted into Debian unstable/sid. It will appear shortly (in next hour or two) for users of unstable/sid. I will back port to Debian 11/stable in 5 days once 2.25 has migrated from unstable/sid to testing/bookworm.

I have also built for Fedora, but I do not have upload rights for this specific package. The update is minor and the Requires for gnome-icon-theme can now be dropped. It would be nice if @fabaff could also build for f36 and f35 if possible allow the users of those supported version can have the latest and greatest rednotebook.

![Screenshot from 2022-05-16 12-49-52](https://user-images.githubusercontent.com/68813857/168590174-85227c8b-f128-4bf1-a8d8-371b44aa0f1a.png)

![Screenshot from 2022-05-16 12-33-49](https://user-images.githubusercontent.com/68813857/168590193-61bd48a4-7cb6-440a-bde2-a2f30ea1eb01.png)
