### ISSUE TITLE
Rednotebook does not start with today's date - Raspberry Pi OS 

### ISSUE THREAD

**Issue by mytor** [jendrikseipp/rednotebook#626]
**Describe the bug**

**Versions:**
- RedNotebook version 2.21 
- Raspberry - Debian 11 Bullseye

**Comment by kathenas** [comment]
What is the exact error you are getting when running rednotebook from the terminal?

**Comment by jendrikseipp** [comment]
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.
