### ISSUE TITLE
Don't start on Ubuntu-Mate 22.04LTS from ppa:rednotebook/stable Unsupportet Python Version 3.10.x~

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [jendrikseipp/rednotebook#633]
**Describe the bug**
<Rednotebook don't start on Ubuntu-Mate 22.04LTS with newest Python 3.10.x installed. But the Flatpak Package is working correctly the problem is just if i installed from ppa:rednotebook/stable and ppa and from ubuntu 22.04 standard ppa>

**To Reproduce**

1. Install Rednotebook on Ubuntu-Mate 22.04LTS over ppa with python 3.10.x installed first
2. Click on 'start or start from the menu or the console '
5. 

**Expected behavior**

**Screenshots**

**Versions:**
- RedNotebook version :
- Operating system and version:

**Log output when reproducing bug**
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/9660082/rednotebook.log)
^This is after i delete the .Rednotebook Directory.
[rednotebook.log](https://github.com/jendrikseipp/rednotebook/files/9660088/rednotebook.log)
^This File i see the first Time i change from Flatpak install to ppa:rednotebook/stable Launchpad install.

**Comment by jendrikseipp** [comment]
Thanks for the report, this is fixed now.
