### ISSUE TITLE
Add Title for Entries

### ISSUE THREAD

**Issue by rogercreagh** [jendrikseipp/rednotebook#642]
Currently an entry is just a block of text. Some formatting is available so it is possible to always start an entry with a heading in a consistent format.

It would make sense to have a title for each entry available as an (optional) separate field from the text description. 

This would also enable an alternative view with a list of entries by title.

**Comment by jendrikseipp** [comment]
I wouldn't want to force users to assign titles to entries. It is already possible to start an entry with a "=== Title ===". That could be parsed automatically for a list-based view.

**Comment by rogercreagh** [comment]
Not to be forced - 
>... available as an (**optional**) separate ...

It would only display in preview (above the text) if the element was present (with a cue in edit mode)

One reason for wanting this is so that there is a clear chunk to be used as the SUMMARY element in a VJOURNAL item (_SUMMARY is really TITLE for a journal entry in my opinion, but the spec calls it SUMMARY for consistency with VEVENT items_)

If the title element was missing when saving to a VJOURNAL then a strategy for providing a summary would be needed - requiring the first line to have a particular format (###For Example in markdown or ===For Eample in yaml) seems restrictive.
