### ISSUE TITLE
Month Summaries

### ISSUE THREAD

**Issue by l3td33r** [jendrikseipp/rednotebook#644]
**Is your feature request related to a problem? Please describe.**
Same as entries for days, but for months; used to describe what we did in a specific month. Short summaries of projects, progress and important things. 

**Describe the solution you'd like**
A separate text edit field used for month summaries. Possibly as a switchable tab at the same place where the word cloud is now.
When we move to next/prev months using the calendar buttons, the month summary changes to current month.

**Comment by jendrikseipp** [comment]
Interesting idea, but outside the scope of what RedNotebook aims to be.
