### ISSUE TITLE
Unexpected powerdown corrupts latest journal file when running from onedrive

### ISSUE THREAD

**Issue by hhafmans** [jendrikseipp/rednotebook#648]
I ran into problems when running Rednotebook from Onedrive. In case the computer hibernates or runs out of power, the journal file gets corrupted.
In my old laptop I had a very poor battery and ran into it mutiple times.
What happens is after the power down the next startup fails. 
When checking further I found it is because the 2022-11.txt journal month file gets corrupted. It shows completely empty. After restoring a backup from that specific file it works OK again.
This happened in both 2.11.1 and 2.25

**Comment by jendrikseipp** [comment]
This should not happen in the newest version, because it only overwrites a month file if the new month file can be read successfully.
