### ISSUE TITLE
Permanent text field in right hand pane

### ISSUE THREAD

**Issue by hhafmans** [jendrikseipp/rednotebook#649]
Since 2011 I have been a daily user of Rednotebook and I like it a lot. 
I like the simplicity and speed of it, but also the search capabilities.
I use it for daily note taking for the project I work on.
I would like it even more if I could have a choice/setting to replace the right hand side tag-pane area with a fixed text field.
That text field is then not limited to only that day, but will be permanent.
It would be a great addition to capture notes that are not connected to a certain day.
Is it possible to add something like this?

**Comment by jendrikseipp** [comment]
Thanks for the suggestion, but this is beyond the goals that RedNotebook tries to achieve.

What you can do, however, is to have entries like 

#general my awesome idea 
#general my second awesome idea

Then you can search for the #general tag and see a list of all your general notes, plus you know when you created them.
