### ISSUE TITLE
rednotebook fails to build with Python 3.12: ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#655]
**Describe the bug**

rednotebook fails to build with Python 3.12: ModuleNotFoundError: No module named 'distutils'

See bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2154962

**Comment by jendrikseipp** [comment]
This should be fixed now. Thanks for the heads up!
