### ISSUE TITLE
2.28.1 translations require update.

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#657]
**Describe the bug**

In 2.28.1 building for Debian unstable/sid, I am getting:

dpkg-source: error: add build/locale/vi/LC_MESSAGES/rednotebook.mo in debian/source/include-binaries if you want to store the modified binary in the debian tarball
dpkg-source: error: cannot represent change to build/locale/wae/LC_MESSAGES/rednotebook.mo: binary file contents changed

Do we need another translations update?

**Comment by jendrikseipp** [comment]
I'm not sure how to fix this. I synced the translations with the weblate service again, but no files changed. Do you have another idea?

**Comment by kathenas** [comment]
> I'm not sure how to fix this. I synced the translations with the weblate service again, but no files changed. Do you have another idea?

After some head scratching as I have never hit this one before. The solution seems to be:

1. Add a file called 'clean' in the 'debian' folder.
2. Add the text below into the 'clean' file...

   build/locale/*/LC_MESSAGES/rednotebook.mo

Now build as normal.

**Comment by kathenas** [comment]
> > I'm not sure how to fix this. I synced the translations with the weblate service again, but no files changed. Do you have another idea?
> 
> After some head scratching as I have never hit this one before. The solution seems to be:
> 
>     1. Add a file called 'clean' in the 'debian' folder.
> 
>     2. Add the text below into the 'clean' file...
>        build/locale/*/LC_MESSAGES/rednotebook.mo
> 
> 
> Now build as normal.

2.28.1 with the fix above has now been accepted into Debian unstable/sid.

Closing.
