### ISSUE TITLE
Flathub: Outdated link for translations

### ISSUE THREAD

**Issue by Atalanttore** [jendrikseipp/rednotebook#660]
The “Translations” button to translate [RedNotebook](https://flathub.org/apps/details/app.rednotebook.RedNotebook) is linking to Launchpad and not to Weblate.

**Comment by jendrikseipp** [comment]
Thanks for the report! I fixed this [here](https://github.com/flathub/app.rednotebook.RedNotebook/pull/18), but we'll have to wait until the builds succeed before I can merge this.
