### ISSUE TITLE
2.29.2 changes break translation generation on Fedora/EPEL.

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#666]
2.29.2 changes break translation generation on Fedora/EPEL.

```
+ /usr/lib/rpm/find-lang.sh /builddir/build/BUILDROOT/rednotebook-2.29.2-1.fc37.x86_64 rednotebook
No translations found for rednotebook in /builddir/build/BUILDROOT/rednotebook-2.29.2-1.fc37.x86_64

RPM build errors:
```

**Comment by jendrikseipp** [comment]
Thanks for the report! I ran Fedora's build steps locally and could reproduce the problem. Will look into a fix ASAP.

**Comment by jendrikseipp** [comment]
After many attempts I think I found a suitable solution for this. Please give version 2.29.3 a try :-)

**Comment by kathenas** [comment]
The changes look good and 2.29.3 has been uploaded to the relevant sections in Debian and Fedora/EPEL.

**Comment by jendrikseipp** [comment]
Great, thanks!
