### ISSUE TITLE
Keyboard short-cuts missing/do not function

### ISSUE THREAD

**Issue by stevenbrown2** [jendrikseipp/rednotebook#676]
**Describe the bug**
Recently updated to version 2.29.3. The first thing I noticed was that the keyboard short-cut to save (Ctrl-S) did not work and is not shown in Journal Menu Dialog.  Upon further investigation, the ALT menu shortcuts do not work for Journal (Alt-J) and Format (Alt-F) menu options.  When you hold the Alt key down the J and F underline as expected but when you press J or F there is no response.  The respective menu does not display.  Edit, Insert and Help work as expected.

**To Reproduce**

1. Hold the ALT key
2. Press J or F

**Expected behavior**
1. When you press Ctrl-S, expect Journal to save in default location
2. When you press Alt-J, expect Journal menu to be displayed
3. When you press Alt-F, expect format menu to be displayed.

**Screenshots**

**Versions:**
- RedNotebook version 2.29.3
- Operating system and version: Windows 11 Pro 22H2 build 22621.1265

**Log output when reproducing bug**
nothing in the log file relating to this issue

**Comment by jendrikseipp** [comment]
This has been fixed in version [2.29.6](https://github.com/jendrikseipp/rednotebook/releases/tag/v2.29.6)
