### ISSUE TITLE
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.

### ISSUE THREAD

**Issue by PnYMaT** [jendrikseipp/rednotebook#680]
**Describe the bug**
When check update for app.rednotebook.RedNotebook on flatpak, i have this warning :
"Looking for updates…
Info: org.gnome.Platform//42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   app.rednotebook.RedNotebook
Nothing to do."

**To Reproduce**
$ flatpak update app.rednotebook.RedNotebook

**Expected behavior**
Using more recent runtime

**Screenshots**

**Versions:**
- RedNotebook version : 2.29.3
- Operating system and version: Debian 11 x64 Stable

**Log output when reproducing bug**
Looking for updates…
Info: org.gnome.Platform//42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   app.rednotebook.RedNotebook
Nothing to do.

Thanks for help.

**Comment by jendrikseipp** [comment]
Thanks for the report! Could you please file it at https://github.com/flathub/app.rednotebook.RedNotebook again, so the right people see it?

**Comment by PnYMaT** [comment]
> Thanks for the report! Could you please file it at https://github.com/flathub/app.rednotebook.RedNotebook again, so the right people see it?

Hi, it is done :)

https://github.com/flathub/app.rednotebook.RedNotebook/issues/23
