### ISSUE TITLE
Word cloud no longer appearing

### ISSUE THREAD

**Issue by allstar87** [jendrikseipp/rednotebook#681]
Using version 2.29.3, flatpak, on Linux Mint 21.1 Cinnamon.

Recently I guess there's been an update that seems to have broken most of the core functionality of the app.

The common word cloud just...doesn't appear anymore.  The space below the search bar where it used to appear is just blank.  Search results appear there if you type something in the search bar, but the word cloud doesn't show up.  Options for it are still in the options menu.

**Comment by jendrikseipp** [comment]
Thanks for the report! This should be fixed now in version 2.29.4. Can you confirm?
