### ISSUE TITLE
Saving data by pressing hotkey Ctrl+S not works

### ISSUE THREAD

**Issue by vodolaz095** [jendrikseipp/rednotebook#690]
**Describe the bug**
Hotkey Ctrl+S for saving content doesn't work - looks like hotkey is not assignable

**To Reproduce**
1. Open rednotebook
2. Press CTRL+S
3. Nothing happens

**Expected behavior**
After pressing Ctrl+S blog content is saved

**Screenshots**
![rednotebook](https://user-images.githubusercontent.com/954485/235135018-19c44646-168f-46bd-879f-10418682dc6e.jpg)

**Versions:**

- 2.29.5
- OS: Fedora 36

**Log output when reproducing bug**

**Comment by jendrikseipp** [comment]
Thanks for the report! I can confirm the problem. The Ctrl+S hotkey has no effect.
