### ISSUE TITLE
Command line option --minimized doesn't work

### ISSUE THREAD

**Issue by Cris70** [jendrikseipp/rednotebook#694]
**Describe the bug**
Command line option --minimized doesn't work ( see #229 )

**To Reproduce**
Drop to command line, type "rednotebook --minimized"

**Expected behavior**
Rednotebook starts  minimized

**Screenshots**

**Versions:**
- RedNotebook version 2.29.6 (flatpack)
- Operating system and version: openSuse Tumbleweed

**Log output when reproducing bug**
```
~ > /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=rednotebook app.rednotebook.RedNotebook --minimized
INFO     Using GtkSourceView 4
Adding /app/lib/python3.10/site-packages to sys.path
INFO     Available versions of the WebKit2 namespace: ['4.1']

(rednotebook:2): Gtk-WARNING **: 11:49:37.261: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 11:49:37.261: Failed to load module "canberra-gtk-module"
INFO     Loaded version of the WebKit2 namespace: 4.1
INFO     Locale path: /usr/share/locale
WARNING  Failed to set user-preferred locale settings: unsupported locale setting
usage: rednotebook [-h] [--version] [--date START_DATE] [journal]
rednotebook: error: unrecognized arguments: --minimized
```

**Comment by jendrikseipp** [comment]
The --minimized option has been removed in newer versions.

**Comment by Cris70** [comment]
@jendrikseipp thank you for the update.
May I know the rationale behind this decision?
I did find that option very valuable. Is it something that can be reverted?

**Comment by jendrikseipp** [comment]
There might be something in the changelog about this. IIRC this behavior is not supported well across platforms. It can't be resurrected, sorry.
