### ISSUE TITLE
asterisk as an alternative for bullet list

### ISSUE THREAD

**Issue by opoplawski** [jendrikseipp/rednotebook#697]
**Is your feature request related to a problem? Please describe.**
I tend to copy/paste some of my journal entries into a mediawiki page.  Mediawiki uses * for bullet lists and I like to use those a lot.  Perhaps rednotebook could treat those like bullet list entries as well.

**Describe alternatives you've considered**
Just never using preview mode.

**Versions:**
- RedNotebook version : 2.29.6
- Operating system and version: AlmaLinux 8.7

Otherwise - thank you very much for creating this software - it looks quite nice.

**Comment by jendrikseipp** [comment]
This will be possible if/when we switch to Markdown.
