### ISSUE TITLE
Color Icons

### ISSUE THREAD

**Issue by stevenbrown2** [jendrikseipp/rednotebook#700]
Same version 2.29.6 on 2 different machines.
Windows 10
![image](https://github.com/jendrikseipp/rednotebook/assets/78856522/9dbac07c-8f90-4b5b-a2cf-5daf8d1dcb48)

Windows 11
![image](https://github.com/jendrikseipp/rednotebook/assets/78856522/41972b02-9940-4f92-b949-9dd12db5be22)

Is there a settings file somewhere where one can turn on/change default icon set?  No modifications were made during install, the only difference is the OS version.

Not critical - just asking.

Thanks,
Steve

**Comment by jendrikseipp** [comment]
Interesting that the OS version makes a difference here. No, I don't know a setting for changing this.
