### ISSUE TITLE
RedNotebook/KDE - keyboard freeze, sometimes KDE freeze

### ISSUE THREAD

**Issue by nobanzai** [jendrikseipp/rednotebook#707]
For some time now I have a problem with the keyboard on my notebook, when using RedNotebook (KDE) for a while and having written or copied lots of contents. It becomes extremely slow, i.e. only one or two keypresses are shown every 10 seconds. When this happens, not only RedNotebook is affected, but all applications, where text can be entered, i.e. OO Writer, graphical  terminals or even dialog boxes of any kind. It happens with the internal notebook keyboard and also with an external USB keyboard. Special keyboard shortcuts like Alt-F4 or Ctrl-F5 are working as expected. Switching to a Linux console with Ctrl-Alt-[0-9] is working, too. In the Linux console typing works without any problems then. Switching back to KDE again/still shows the problem.
The only "solution" I found is to logout and login again. If I start RedNotebook again, the keyboard works as expected for a while, until the same problem reoccurs. The intervals the problem shows up vary between once an evening to every 10 minutes.
Additionally the problem gets worse, if I don't logout shortly after the problem occurs. In this case, logout isn't even possible, I have to kill the session. One can't start KDE apps after a while, for example systemsettings5. And a few minutes later the network connection gets dropped randomly.
I checked the hardware of the machine with DELL's integrated utility and also ran a full pass of mentest86, but no problems were found.
There is nothing shown in the rednotebook.log or in the system journal, that would fit to this problem.

Machine:  Type: Convertible System: Dell product: XPS 13 9310 2-in-1 v: N/A
System: openSUSE Tumbleweed 20230509
RedNotebook: rednotebook-2.29.6-1.1.noarch

My diary is about 35 meg in size.
I am not really sure, if this is a RedNotebook problem, but because it always happens, when using RedNotebook, ...
Memory corruption?

**Comment by jendrikseipp** [comment]
This sounds like a problem with your computer, not with RedNotebook.
