### ISSUE TITLE
[feature request] Automatic/scheduled backups

### ISSUE THREAD

**Issue by mdeguzis** [jendrikseipp/rednotebook#710]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Automatic backups to an alternate folder

**Describe alternatives you've considered**
It would be nice to have this as a CLI option I can implement via cron myself so I can log output, or a way to just do it in the program

**Versions:**
- RedNotebook version :
```
$ rednotebook --version
Adding /usr/share/rednotebook to sys.path
RedNotebook 2.24
```

- Operating system and version:
```
Linux pop-os 6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jendrikseipp** [comment]
Writing a cron job for this is straightforward: create a cron file that zips your journal dir and gives it a unique name (based on the date).
