### ISSUE TITLE
Debian Package Requires Incorrect Dependency; Warning report

### ISSUE THREAD

**Issue by BlueNalgene** [jendrikseipp/rednotebook#713]
**Describe the bug**
The Ubuntu package does not list Webkit2 4.1 as a dependency, leading to warnings.  The package dependency should either demand ``gir1.2-webkit2-4.1`` or not perform the Webkit2 version check.

**To Reproduce**

1. Install rednotebook from the PPA without any custom dependencies.
2. Run and observe warning.

**Expected behavior**

No warning.

**Screenshots**

**Versions:**
- RedNotebook version : 2.29.6
- Operating system and version:
```
OS: Kubuntu 22.04.2 LTS x86_64 
Host: TITAN Standard 
Kernel: 5.15.0-76-generic 
Uptime: 9 days, 12 hours, 9 mins 
Packages: 3182 (dpkg), 12 (flatpak), 13 (snap) 
Shell: bash 5.1.16 
Resolution: 3840x2160, 3840x2160, 2560x1440 
DE: Plasma 5.24.7 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
Terminal Font: Hack 12 
CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 3.300GHz 
GPU: AMD ATI 06:00.0 Cezanne 
GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q 
Memory: 8816MiB / 31487MiB
```

**Log output when reproducing bug**

```
INFO     Using GtkSourceView 4
Adding /usr/share/rednotebook to sys.path
INFO     Available versions of the WebKit2 namespace: ['4.0']
WARNING  WebKit2 4.1 not found. Trying to use arbitrary version. Error message: 'Namespace WebKit2 not available for version 4.1'
/usr/share/rednotebook/rednotebook/util/filesystem.py:59: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit2
INFO     Loaded version of the WebKit2 namespace: 4.0
INFO     Locale path: /usr/share/locale
[truncated for space]
```

**Comment by kathenas** [comment]
Hi,

The runtime dependency has to be on an API version webkit package and that is currently:

gir1.2-webkit2-4.0

The reason for this in Debian was to allow backports for Debian 11 (bullseye). Now we have the recent release of a new Debian stable 12 (bookworm) which has gir1.2-webkit2-4.1, the dependency for future releases can be updated.

Ubuntu 22.04 (jammy) has gir1.2-webkit2-4.1, so this is not an issue.

This change would end any backports for distribution versions prior to Debian 12 and Ubuntu 22.04. I do not see this as a problem for desktop/rednotebook users and users of Debian or Ubuntu as I would assume the use of recent versions.

I will personally change the dependency to gir1.2-webkit2-4.1 in the next release that goes into Debian and in turn that will be imported into Ubuntu. For Ubuntu 22.04.x I will prepare a backport and get it sponsored in.

Regards

Phil

**Comment by kathenas** [comment]
> Hi,
> 
> The runtime dependency has to be on an API version webkit package and that is currently:
> 
> gir1.2-webkit2-4.0
> 
> The reason for this in Debian was to allow backports for Debian 11 (bullseye). Now we have the recent release of a new Debian stable 12 (bookworm) which has gir1.2-webkit2-4.1, the dependency for future releases can be updated.
> 
> Ubuntu 22.04 (jammy) has gir1.2-webkit2-4.1, so this is not an issue.
> 
> This change would end any backports for distribution versions prior to Debian 12 and Ubuntu 22.04. I do not see this as a problem for desktop/rednotebook users and users of Debian or Ubuntu as I would assume the use of recent versions.
> 
> I will personally change the dependency to gir1.2-webkit2-4.1 in the next release that goes into Debian and in turn that will be imported into Ubuntu. For Ubuntu 22.04.x I will prepare a backport and get it sponsored in.
> 
> Regards
> 
> Phil

See PR: https://github.com/jendrikseipp/rednotebook/pull/716

This will resolve the issue, but lead to an additional testing time requirement.

Regards

Phil
