### ISSUE TITLE
lost all data after I asked it to remind me during my next session

### ISSUE THREAD

**Issue by haricash** [jendrikseipp/rednotebook#719]
I've been using rednotebook's journal for two weeks now and I haven't done a backup yet. Today when I opened rednotebook I asked it to remind me to backup next time and I tried accessing my older notes to find them all gone. I checked the directory where I had them stored (it was at HOME/.rednotebook/data) but I only got a blank file. I had also stored the data at another location (HOME/.rednotebook/log) and I find everything missing there too. How do I recover my data?

**Comment by jendrikseipp** [comment]
That's strange. RedNotebook will only delete old month files once it has written and checked new ones. I recommend searching your whole computer for the filename 2023-08.txt

**Comment by haricash** [comment]
My recent entry seems to have overwritten all other previous entries. Prior to that, I couldn't find a single file named 2023-08.txt. I had no removable storage devices attached either, so I couldn't have mistakenly stored the file location there either.

**Comment by jendrikseipp** [comment]
Sorry, there's not much more I can do to help you here.
