### ISSUE TITLE
Build option for the portable version?

### ISSUE THREAD

**Issue by iameijaz** [jendrikseipp/rednotebook#722]
Hello there, I was hoping to find a way to build a portabel exe file for this after some modifications, and i am using appveyor to build this and I am getting a setup file instead. Any help would be appreciated.

**Comment by jendrikseipp** [comment]
Next to the installer exe file, there should be a zip file containing the standalone executable file.

**Comment by iameijaz** [comment]
But, can't we have just a single EXE file which acts like a portable version?

**Comment by iameijaz** [comment]
Alright.Thanks. But can you tell me which different exe would we need to accomplish that?
