### ISSUE TITLE
Make rednotebook use the Installation different directory to save cfg, data and log files

### ISSUE THREAD

**Issue by iameijaz** [jendrikseipp/rednotebook#723]
Since I have normally get operating system issues and for that I want to make a build which allows me to use a different directory instead of the user directory/.rednotebook for log and data files, how can I do that?

**Comment by jendrikseipp** [comment]
That's currently not possible. But #404 is concerned with that.

**Comment by iameijaz** [comment]
if I found a solution for this, can I commit it?

**Comment by jendrikseipp** [comment]
We're discussing a solution for this in #404, but currently I think it's best to keep things the way they are for backwards compatibility.
