### ISSUE TITLE
After upgrade, can no longer copy in preview mode

### ISSUE THREAD

**Issue by tedgin** [jendrikseipp/rednotebook#732]
**Describe the bug**

In a previous version of Rednotebook (I don't know what the version number was), I could use Ctrl+C to copy formatted content from Rednotebook when it was in preview mode, but now I cannot.

**To Reproduce**

1. View a day with journal content.
2. Switch to preview mode.
3. Select some of the formatted text in the preview view.
4. Press Ctrl+C or the _Copy_ item from the _Edit_ menu.
5. Change your focus to another application's window, like a Gmail Compose window.
6. Press Ctrl+V to paste.

**Expected behavior**

I expect the selected text to be displayed in the other application's window.

**Screenshots**

N/A

**Versions:**
- RedNotebook version 2.31:
- Operating system and version: Ubuntu 22.04

**Log output when reproducing bug**
```
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/rednotebook/rednotebook/gui/menu.py", line 373, in on_copy_menu_item_activate
    self._get_active_editor_widget().emit("copy_clipboard")
TypeError: <main_window.Preview object at 0x7efce9b2d140 (rednotebook+gui+main_window+Preview at 0x558e116d1d50)>: unknown signal name: copy_clipboard
```

**Comment by jendrikseipp** [comment]
Thanks for the report! This is fixed now.
