### ISSUE TITLE
hashtags not shown red in writing mode and bold not shown bold, if making a bullet point list

### ISSUE THREAD

**Issue by janival** [jendrikseipp/rednotebook#744]
this is small but a bit annoying thing. When i use hashtags I would like the text to be automatically red, and when I use ** for bold, I would like it to be shown automatically bold.

This works, if I do this in normal text, but if I make a bullet point list, starting the line with '-', it does not work anymore.

So
This kind #text looks **correct**
- This kind of #text does not look **correct**

**Comment by jendrikseipp** [comment]
Thanks for the report! This is fixed now.
