### ISSUE TITLE
Change made in commit d2ffc80 - GPL-3.0+

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#745]
Hi Jendrik,

The last commit changes the project license to GPL-3.0+.

``
  <project_license>GPL-3.0+</project_license>
``

Would this mean the whole project is now this license?

If yes, the LICENSE file in the root of the repo needs updating and the 'Files: *' and likely any specific sections upon agreement of any co-contributors in 'debian/copyright' would probably need to be updated.

Thoughts?

Regards

Phil

**Comment by jendrikseipp** [comment]
Good catch! I reverted the change.
