### ISSUE TITLE
Drop python in favor of Windows 7(and earlier) compatibility

### ISSUE THREAD

**Issue by powerbroker** [jendrikseipp/rednotebook#753]
Install and run on Win7, even x86 or x64. 
Enjoy startup crash because python 3.9 failure because there is no api-ms-win-core-path-l1-1-0.dll in Windows 7

Such a simple software muzz run on as many OSes, as possible and never limit compatibility by used third-party components(it's definitely possible to issue SQL-requests w/o pythons, etc.)

Workaround: https://remontka.pro/api-ms-win-core-path-l1-1-0-dll/

**Comment by jendrikseipp** [comment]
Windows 7 is EOL (https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962), so we can't guarantee that newer versions of RedNotebook will run on it. But older versions should run even on Windows 7.
