### ISSUE TITLE
Focus not respected - Impossible to paste into search widget

### ISSUE THREAD

**Issue by carygravel** [jendrikseipp/rednotebook#766]
**Describe the bug**
I had copied some text and tried to paste it into the search widget, but the text was pasted instead into the text window.

**To Reproduce**
1. Copy text
2. Give the search widget focus
3. Paste text
4. The text appears in the text window, not the search widget.

**Expected behavior**
I expected the text to appear in the search window

**Versions:**
- RedNotebook version v2.33
- Operating system and version: Debian testing, up to date.

**Comment by jendrikseipp** [comment]
Thanks for reporting this! Fixed now.
