### ISSUE TITLE
Error pasting text in search box with Ctrl+v

### ISSUE THREAD

**Issue by mamaicas** [jendrikseipp/rednotebook#772]
**Describe the bug**
When you paste text using Ctrl+v in search box the text is pasted in notepad area, not in search box
If you paste text using mouse right button > paste, or with Shift+insert it works properly

**To Reproduce**

1. Copy some text into de clipboard
2. Do click inside 'search box'
3. Press Ctrl+v
4. The text is pasted in edition area not in the search box

**Expected behavior**
The text should be pasted in search box

**Versions:**
- RedNotebook version 2.33, 2.31 for Windows
- Operating system and version: Windows 11

**Comment by jendrikseipp** [comment]
This should be fixed in version 2.34 now. Can you please check?

**Comment by mamaicas** [comment]
Yes, is fixed!
Thanks
