### ISSUE TITLE
Option to disable word cloud and code block construct. 

### ISSUE THREAD

**Issue by leimath** [jendrikseipp/rednotebook#780]
**Is your feature request related to a problem? Please describe.**

Hi! This is a really awesome tool.
I mainly use rednotebook to type my notes in (i know i can use a conventional note taking app). I do this as I like it being arranged with dates and good searchability that I get. Plus the LaTeX export is nice!

1. However due to the volume of my notes, I often would not like to render the word cloud. I couldn't figure out a way so maybe a toggle in the options to disable it will be nice.
2. Sometimes I am in need of adding code blocks (even in regular journalling) so maybe plain backticks generated code block area would be nice? Not asking for syntax highlighting but just pure code blocks may be nice. This would be also helpful for maually drawn tables since they can be put in a stylistically different way.

**Describe the solution you'd like**

1. Option in `Preferences` to disable the word cloud. Or a wildcard `*` or `~` to put in the exclusion list to disable any words from being in the word cloud.
2. `\`` generated code blocks to enter code in to show them stylistically in a different way. 

**Describe alternatives you've considered**

**Versions:**
- RedNotebook version : From the system package manager of fedora.
- Operating system and version: i3 + Fedora 41

**Comment by jendrikseipp** [comment]
You're in luck, both requests are already possible (see https://rednotebook.app/help.html): 
* You can hide the word cloud by adding the regular expression .* to the blacklist. This will filter out all words. 
* To insert preformatted text preserving newlines and spaces, you can use the backquotes (`). Use 2 backquotes for inline insertions and 3 backquotes if you want to insert a whole paragraph.
