### ISSUE TITLE
RTL Texts in Preview mode get wrong direction

### ISSUE THREAD

**Issue by metemaddar** [jendrikseipp/rednotebook#781]
**Describe the bug**
In Preview mode, RTL Paragraphs, for example Persian Text (Paragraphs that start with RTL characters)  keep wrong (LTR) direction. 
However in Edit mode,they seem right. They automatically get rtl direction.
So we need a change for Preview mode.

**To Reproduce**

1. Add a paragraph starting with RTL character. For example: "امروز"
2. Click on preview mode icon to get into preview.
3. We expect the "امروز" Should go to the right. But it goes to left.

**Expected behavior**
The RTL Paragraphs need to get RTL and Right aligned.

**Screenshots**
RTL Text (Persian) is getting wrong direction in Preview mode:
![RTL (Persian) Text showing in opposite direction in Preview mode](https://github.com/user-attachments/assets/08ea9666-ae9a-496d-a45c-c88af6fa623d)

RTL Text is getting correct direction (RTL) in edit mode:
![RTL Text showing correct in edit mode](https://github.com/user-attachments/assets/19fbfdc5-cc2a-4663-8dee-4bbdf62cf8f0)

**Versions:**
- RedNotebook version : 2.32 and main branch.
- Operating system and version: Ubuntu 24.04

**Works done to fix this issue**
Me and my friends have already determined the problem and some points to change, like rendering engines, html data, css styles, and tried some changes to fix the issue for preview mode. However it was not completely fixed but we got great understanding of underlying code. I invite the folks to comment the experiences if needed, or we can continue fixing the bug and talk at PR.

**Log output when reproducing bug**

> 2024-11-03 23:03:53,657 INFO     Writing log to file "/home/<USER>/.rednotebook/rednotebook.log"
> 2024-11-03 23:03:53,657 INFO     System encoding: utf-8
> 2024-11-03 23:03:53,657 INFO     Language code: en_US
> 2024-11-03 23:03:53,670 INFO     Spell checking languages: ['en', 'en_AU', 'en_CA', 'en_GB', 'en_US']
> 2024-11-03 23:03:53,670 INFO     Spell checking dictionaries: [('en', <Enchant: Aspell Provider>), ('en_AU', <Enchant: Aspell Provider>), ('en_CA', <Enchant: Aspell Provider>), ('en_GB', <Enchant: Aspell Provider>), ('en_US', <Enchant: Aspell Provider>)]
> 2024-11-03 23:03:53,761 INFO     Using LibYAML
> 2024-11-03 23:03:53,762 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
> 2024-11-03 23:03:53,764 INFO     Running in portable mode: False
> 2024-11-03 23:03:53,764 INFO     First Start: True
> 2024-11-03 23:03:53,764 INFO     RedNotebook version: 2.32
> 2024-11-03 23:03:53,765 INFO     System info: machine: x86_64, platform: Linux-6.8.0-48-generic-x86_64-with-glibc2.39, processor: x86_64, python_version: 3.12.3, release: 6.8.0-48-generic, system: Linux, GTK: (3, 24, 41), Glib: (2, 80, 0), PyGObject: (3, 48, 2), YAML: 6.0.1, WebKit2: (2, 46, 1)
> 2024-11-03 23:03:53,879 DEBUG    Default font: Ubuntu Sans 11
> 2024-11-03 23:03:53,879 DEBUG    Default size: 11.0
> 2024-11-03 23:03:53,961 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
> 2024-11-03 23:03:53,961 INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
> 2024-11-03 23:03:53,961 DEBUG    Start compiling regexes
> 2024-11-03 23:03:53,961 DEBUG    Finished
> 2024-11-03 23:03:53,966 DEBUG    Tray icon visible: False
> 2024-11-03 23:03:53,969 INFO     Opening journal at '/home/<USER>/.rednotebook/data'
> 2024-11-03 23:03:53,970 DEBUG    Starting to load files in dir "/home/<USER>/.rednotebook/data"
> 2024-11-03 23:03:53,970 DEBUG    Finished loading files in dir "/home/<USER>/.rednotebook/data"
> 2024-11-03 23:03:53,983 INFO     Adding example content on 2024-11-03
> 2024-11-03 23:03:54,005 DEBUG    Update the cloud
> 2024-11-03 23:03:54,006 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:03:54,006 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:03:54,009 DEBUG    Cloud updated
> 2024-11-03 23:03:54,010 INFO     Last backup was made 0 days ago
> 2024-11-03 23:04:50,780 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:04:50,781 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:04:50,781 DEBUG    Add mathjax code: False
> 2024-11-03 23:05:51,000 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:05:51,000 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:05:51,001 DEBUG    Add mathjax code: False
> 2024-11-03 23:06:06,423 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:06:06,423 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:06:06,423 DEBUG    Add mathjax code: False
> 2024-11-03 23:06:11,406 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:06:11,406 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:06:11,406 DEBUG    Add mathjax code: False
> 2024-11-03 23:06:18,665 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:06:18,665 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:06:18,665 DEBUG    Add mathjax code: False
> 2024-11-03 23:06:30,151 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:06:30,152 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:06:30,152 DEBUG    Add mathjax code: False
> 2024-11-03 23:06:37,445 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:06:37,445 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:06:37,445 DEBUG    Add mathjax code: False
> 2024-11-03 23:07:03,670 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:07:03,670 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:07:03,670 DEBUG    Add mathjax code: False
> 2024-11-03 23:07:24,793 DEBUG    Background color: rgb(39,39,39)
> 2024-11-03 23:07:24,793 DEBUG    Foreground color: rgb(255,255,255)
> 2024-11-03 23:07:24,793 DEBUG    Add mathjax code: False

**Comment by jendrikseipp** [comment]
This seems to be a problem in the underlying WebkitGtk renderer. Can you try to find out if there's a specific setting that needs to be set for RTL texts to work there?

**Comment by metemaddar** [comment]
> This seems to be a problem in the underlying WebkitGtk renderer. Can you try to find out if there's a specific setting that needs to be set for RTL texts to work there?

Honestly, I have no idea how to let [WebKitWebView](https://webkitgtk.org/reference/webkit2gtk/2.25.3/WebKitWebView.html) to handle auto-direction. But as it is working like a browser I think maybe it can render by [dir=auto](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir). I tried to inject this attribute to the html text, but I don't know why the replace method didn't work. I need to try more to see if it can do the job for us. If it worked, maybe we can also take a look at converter to see if we can inject `dir=ltr` at the convertor function.
