### ISSUE TITLE
Strange upgrading

### ISSUE THREAD

**Issue by Nick222** [jendrikseipp/rednotebook#788]
I do not know - is it bug or not...

Xubuntu 24.10
Upgrade Rednotebook from 2.36 to 2.37

>  …/rednotebook_2.37-0~202412182026~ubuntu24.10.1_all.deb …
> Распаковывается rednotebook (2.37-0~202412182026~ubuntu24.10.1) на замену (2.36-0~202411241815~ubuntu24.10.1) …
> Настраивается пакет rednotebook (2.37-0~202412182026~ubuntu24.10.1) …
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:872: SyntaxWarning: invalid escape sequence '\s'
  'title1'               : '~A~\section*{\a}'     ,
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:878: SyntaxWarning: invalid escape sequence '\s'
  'numtitle1'            : '\n~A~\section{\a}'      ,
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:913: SyntaxWarning: invalid escape sequence '\l'
  'bar2'                 : '\\rule{\linewidth}{1mm}',
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:1323: SyntaxWarning: invalid escape sequence '\('
  'listItemOpen'          : '.IP \(bu 3\n',
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:2738: SyntaxWarning: invalid escape sequence '\.'
  basename = re.sub('\.(txt|t2t)$','',infile)
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:2929: SyntaxWarning: invalid escape sequence '\s'
  cfgregex  = re.compile("""
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:2937: SyntaxWarning: invalid escape sequence '\s'
  prepostregex = re.compile("""
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:2952: SyntaxWarning: invalid escape sequence '\s'
  guicolors = re.compile("^([^\s]+\s+){3}[^\s]+") # 4 tokens
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:2977: SyntaxWarning: invalid escape sequence '\s'
  value = re.split('\s+', value)
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:3452: SyntaxWarning: invalid escape sequence '\|'
  m = re.search('\a(\|+)$', cell)
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:3559: SyntaxWarning: invalid escape sequence '\|'
  m = re.search(' (\|+) *$', line)
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:3565: SyntaxWarning: invalid escape sequence '\|'
  line = re.sub(' (\|+)\| ', '\a\\1 | ', line)
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:3571: SyntaxWarning: invalid escape sequence '\|'
  ret['cells'] = [re.sub('\a\|+$','',x) for x in ret['cells']]
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:3868: SyntaxWarning: invalid escape sequence '\s'
  re.match('^\s*<center>.*</center>\s*$', lines[0]):
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:4151: SyntaxWarning: invalid escape sequence '\.'
  elif flag == 'F': x = re.sub('\.[^.]*$','',info['name'])
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:4155: SyntaxWarning: invalid escape sequence '\.'
  elif flag == 'e': x = re.search('.(\.([^.]+))?$', info['name']).group(2) or ''
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:4382: SyntaxWarning: invalid escape sequence '\.'
  val = [re.sub('(?i)\.sty$','',x) for x in val]
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:4536: SyntaxWarning: invalid escape sequence '\#'
  txt = re.sub('<','<\#60>',txt)
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:4583: SyntaxWarning: invalid escape sequence '\ '
  "Replace any Escape Char \ with a text mask (Input: str or list)"
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:4589: SyntaxWarning: invalid escape sequence '\ '
  "Undo the Escape char \ masking (Input: str or list)"
> /usr/share/rednotebook/rednotebook/external/txt2tags.py:4923: SyntaxWarning: invalid escape sequence '\s'
  if re.match('^\s+$', rest):

After that Rednotebook start and work good...

**Comment by jendrikseipp** [comment]
Thanks for the report! This should now be fixed in the development version.
